### ISSUE TITLE
What about Windows environment?

### ISSUE THREAD

**Issue by ginzunza** [lorisleiva/laravel-deployer#1]
It works on windows environment?.

regards

**Comment by lorisleiva** [comment]
Yes, it should work since the underlying technology is only php. However I do not own a Windows local machine nor a Windows server. Thus if you have the chance to try Laravel Deployer on a Windows machine, your feedback is greatly appreciated.

**Comment by ArtemMolotov** [comment]
@lorisleiva, hi, It does not work at all...

![](https://habrastorage.org/webt/ig/2u/qo/ig2uqo76y3f2hpqgb4bvmyigdba.png)

**Comment by lorisleiva** [comment]
@ArtemMolotov Thanks for this info. However this constraint is only if your server is not POSIX compliant. It does not say if it works when deploying from a Windows computer to a linux server for example.

**Comment by ArtemMolotov** [comment]
@lorisleiva, yes, you are right, thanks. But we have this error with `locally-built strategy` too:
![image](https://user-images.githubusercontent.com/22825202/48077222-8a635880-e1ef-11e8-9ca2-f7a62f9181e4.png)

**Comment by ArtemMolotov** [comment]
Tell me, please, is it possible to override `deploy:prepare` task and replace `bash` commands with `php` code?

**Comment by lorisleiva** [comment]
@ArtemMolotov Ah yes well spotted. You can override any task including `deploy:prepare`. Let me know how you get on.

**Comment by ArtemMolotov** [comment]
Deploy with the "basic" strategy successfully works on Windows (after solve SSH's problems).
Overriding the Deployer's tasks (not one) for work with 'locally-built' strategy can be labor-intensive.
