### ISSUE TITLE
deployer should remove deploy.lock if deployment failed

### ISSUE THREAD

**Issue by mehrdaad** [lorisleiva/laravel-deployer#10]
deployer should remove ``deploy.lock`` in ``.dep`` directory if deployment is failed since it would prevent subsequent deployments.

**Comment by lorisleiva** [comment]
This should already be the case. By default the task `deploy:unlock` is hooked after `deploy:fail`. Could you please provide more information on how you hit this problem?

**Comment by cmarfil** [comment]
Hello,
I have the same problem when manually exiting deploy:

![image](https://user-images.githubusercontent.com/798849/38766865-9f3dcb46-3fd8-11e8-87c4-371b976804ec.png)

How to solve it? Thanks.

**Comment by lorisleiva** [comment]
Hello, yes when manually exiting deployment, [unlocking also has to be done manually](https://deployer.org/docs/flow#deploy:lock). Simply run `dep deploy:unlock` from your local machine. Or if you prefer the Laravel Deployer way: 
```bash
php artisan deploy:run deploy:unlock
```

Hope this helps.

**Comment by mehrdaad** [comment]
Yes ``deploy:unlock`` is being fired but ``dep.lock`` is not removed.  
process:  
```
➤ Executing task deploy:prepare
root@x.x.x.x's password: 
✔ Executing task deploy:lock
✔ Executing task deploy:release
✔ Executing task deploy:update_code
✔ Executing task deploy:shared
➤ Executing task copy:env
root@x.x.x.x's password: 
✔ Executing task deploy:failed
➤ Executing task deploy:unlock

```
After sshing to server, still there is a ``deploy.lock`` in the ``.dep`` directory.

**Comment by lorisleiva** [comment]
Hmm... that is odd. Does the `deploy:unlock` task run successfully? Do you deploy using some host filtering?

**Comment by mehrdaad** [comment]
I think so, I will test again and will give detailed results after work.

**Comment by mehrdaad** [comment]
Apparently, it runs. But does not execute if deployment is interrupted with Ctrl+C.  
Also, sometimes deployer does not ask password from me which is weird!

**Comment by lorisleiva** [comment]
* Regarding the interrupted deployment, please see [my previous message](https://github.com/lorisleiva/laravel-deployer/issues/10#issuecomment-381318196) on this thread
* Regarding the password, I'm guessing deployer simply does not need to ask your password if you've recently entered it.

**Comment by AlifAbhiesa** [comment]
i'm stuck in here

![image](https://user-images.githubusercontent.com/27193997/97296996-05fabc00-1884-11eb-9c79-a369294cc19a.png)
