### ISSUE TITLE
variable --revision

### ISSUE THREAD

**Issue by Mxrck** [lorisleiva/laravel-deployer#101]
I'm looking for a way to get the variable `revision` just like we can get `branch` to use in a recipe, but I can't find any docs about that.

Currently I have the following recipe:

```php
task('command:update-version', artisan('command:update-version-number {{branch}}'));
```

When I execute with Gitlab CI the following script:

```php
php artisan deploy production.host --branch=${CI_COMMIT_TAG}
```

Everything works great, but i want to use for a testing environment the specific branch "develop", I know i can execute `php artisan deploy testing.host --branch=develop` directly, but I want to show the current commit, so I need to use `php artisan deploy testing.host --revision=${CI_COMMIT_SHA}`.

The deploy works correctly, but when it try to execute the recipe:

```php
task('command:update-version', artisan('command:update-version-number {{revision}}'));
```

It throws the following exception:

```log
Error Output:
================

In Configuration.php line 89:
                                                      
  Configuration parameter `revision` does not exist.  
```

There's a way to get the revision param from the executed command to use in the custom recipe?

**Comment by lorisleiva** [comment]
Hi there 👋 

Looking at the source code of Deployer PHP, it looks like you can access the revision option like this:

```php
task('command:update-version', function () {
    if (input()->hasOption('revision')) {
        $revision = input()->getOption('revision');
        artisan("command:update-version-number $revision")
    }
})
```

I think the reason why the `revision` option is only available as an input option is that it's not something that you can put on your config file directly whereas it makes sense to do that for `branch` for example.

I hope this helps. You can see the a [full example here](https://github.com/deployphp/deployer/blob/d898570ad856be7ccfa80ad4a99da855f96c019b/recipe/deploy/info.php#L22). 🍀

**Comment by Mxrck** [comment]
Hi, thanks for the reply.

I changed my recipe with:

```php
if (input()->hasOption('revision')) {
    $revision = input()->getOption('revision');
    artisan("command:update-version-number {$revision}");
}
else {
    artisan("command:update-version-number {{branch}}");
}
```
but it seems that `$revision` is empty because the command store the default string when param is empty.

Tried:

```php
$revision = input()->getOption('revision');
$revision = input()->getArgument('revision');
$revision = input()->getParameterOption('revision');
```
`$revision` is always empty

**Comment by lorisleiva** [comment]
How weird 🤔 

So even when you provide the option `--revision=FOOBAR` you don't get `FOOBAR` from `input()->getOption('revision')`?

**Comment by Mxrck** [comment]
Yes, the gitlab Job show that it's executing

Gitlab output:
```bash
...
php artisan deploy project-dev.host.test --revision=${CI_COMMIT_SHA}
✈︎ Deploying revision e113d0d4be4f528bde7efe1a14fa84306827831b on project-dev.host.test with basic strategy
...
🚀  Successfully deployed in 17.99s
➤ Executing task command:update-version
✔ Ok
➤ Executing task artisan:view:clear
✔ Ok
Job succeeded
```

Recipe:
```php
task('command:update-version', function () {
    $revision = null;
    try {
        if (input()->hasOption('revision')) {
            $revision = input()->getOption('revision');
        }
        else if (input()->hasArgument('revision')) {
            $revision = input()->getArgument('revision');
        }
        else if (input()->hasParameterOption('revision')) {
            $revision = input()->getParameterOption('revision');
        }
    }
    catch (\Throwable $exception) { /* DO NOTHING */}
    if (!empty($revision)) {
        artisan("command:update-version-number {$revision}");
    }
    else {
        artisan('command:update-version-number {{branch}}');
    }
});
```

`command:update-revision` store "development" if the first param received is empty or null, it works perfectly when I use "branch" instead, I have not tried with `--tag` yet because `--branch` works with tag name and store correctly "v1.0", "v1.1", etc.

I was looking for more docs about "revision" but I can't find any related issue.

**Comment by lorisleiva** [comment]
Okay, thanks for the additional information. I might have an idea of why `input()` does not have the option available. In order to dynamically call different strategies, Laravel Deployer uses the `invoke` function that calls another task from within a task. It might be that CLI options are not passed through the child task.

Something else that we could try is to define the revision as an option. Something like this:

```php
set('revision', function () {
    return input()->getOption('revision');
})
```

And then access revision the same way you access branch: `{{revision}}`.

I'm not sure if this workaround is going to fix the issue but it's worth trying. 🙂 

Let me know how you get on.

**Comment by Mxrck** [comment]
Perfect!, it's working now, thank you :)

Recipe:
```php
set('revision', function () {
    return input()->getOption('revision');
});

task('command:update-version', artisan("command:update-version-number {{branch}}{{revision}}"));
```

![imagen](https://user-images.githubusercontent.com/2360493/56098543-f5176f00-5ec6-11e9-8939-5fbcecb55f63.png)

**Comment by lorisleiva** [comment]
Awesome! Glad I could help. 🍻
