### ISSUE TITLE
Deploying to same hostname - different stages

### ISSUE THREAD

**Issue by CNSam** [lorisleiva/laravel-deployer#106]
Hi there,

Another one i've come across this evening.

```
'hosts' => [
        'sub.domain.lan' => [
            'deploy_path' => '/a/path/here/production',
            'user' => 'root',
            'stage' => 'production',
            'branch' => 'master'
        ],
        'sub.domain.lan' => [
            'deploy_path' => '/a/path/here/testing',
            'user' => 'root',
            'stage' => 'testing',
            'branch' => 'testing'
        ],
    ],
```

Unfortunately when I run the production with the following `    - php artisan deploy -s upload production` I receive an error stating: "Hostname or stage `production` was not found. "

Are you able to advise what I should do here? I've also tried passing the host to the production one but it still deploys the testing branch.

TIA

**Comment by lorisleiva** [comment]
Hi again,

This is actually very normal since you're redefining the same key of a PHP array.

```php
// This...
'hosts' => [
    'sub.domain.lan' => [ /* Production setup here... */ ],
    'sub.domain.lan' => [ /* Testing setup here... */ ],
],

// ... will always compile to this.
'hosts' => [
    'sub.domain.lan' => [ /* Testing setup here... */ ],
],
```

I'm afraid you have to have one unique hostname per host. Can you not use something like `domain.lan` for production and `testing.domain.lan` for testing?

**Comment by CNSam** [comment]
Hey @lorisleiva,

I did some research on the deployer package and they use 'generic' names for their host keys. So I simply followed this route and it works without issue seemingly:

```
'hosts' => [
        'production' => [
            'hostname' => 'sub.domain.lan',
            'deploy_path' => '/a/path/master',
            'user' => 'root',
            'stage' => 'production',
            'branch' => 'master'
        ],
        'testing' => [
            'hostname' => 'sub.domain.lan',
            'deploy_path' => '/a/path/testing',
            'user' => 'root',
            'stage' => 'testing',
            'branch' => 'testing'
        ],
    ],
```

I then invoke the deployment by using: `php artisan deploy -s upload production`.

**Comment by lorisleiva** [comment]
Of course! Sorry I had forgotten about that one haha. Thanks for sharing!
