### ISSUE TITLE
deploy:unlock fail

### ISSUE THREAD

**Issue by rabol** [lorisleiva/laravel-deployer#111]
The command "cd /var/www/html/mysite/releases/1 && (setfacl -RL -m u:"www-data":rwX -m u:`whoami`:rwX bootstrap/cache)" failed.

  Exit Code: 1 (General error)

  Host Name: XXXXXX

  ================
  setfacl: bootstrap/cache: Operation not supported
  setfacl: bootstrap/cache/.gitignore: Operation not supported
  setfacl: bootstrap/cache/services.php: Operation not supported
  setfacl: bootstrap/cache/packages.php: Operation not supported

**Comment by lorisleiva** [comment]
Hi there 👋 

It looks like you have an issue with `setfacl` on your host.

You can either:
- Try to [solve this issue on your host](https://www.google.com/search?q=setfacl+operation+not+supported&oq=setfacl+operation+not+supported).
- Try to use another `writable_mode` option.

<img width="504" alt="Screenshot 2019-05-17 at 12 54 50" src="https://user-images.githubusercontent.com/3642397/57926573-8fdae300-78a3-11e9-896f-f0158df2e885.png">
