### ISSUE TITLE
Include own recipe / task does not work as described

### ISSUE THREAD

**Issue by rabol** [lorisleiva/laravel-deployer#112]
I'm trying to include a new task that will create / copy the .env
in the root of my project I have create a folder called recipe and in the folder I have created project_recipe.php

in the config/deploy.php i have

    'include' => [
       '/recipe/project_recipe.php',
    ],

also tried with several combination where i add ../ to see if that helps

 

but my recipe file is not included

Warning: require(/XXXX/code/web/testproject/app/recipe/project_recipe.php): failed to open stream: No such file or directory in /XXXX/code/web/testproject/vendor/lorisleiva/laravel-deployer/.build/deploy.php on line 11

**Comment by neolikotsi** [comment]
It works without the first `/`
```php
'include' => [
   'recipe/project_recipe.php',
],
```
