### ISSUE TITLE
 There are no commands defined in the "deploy" namespace.

### ISSUE THREAD

**Issue by rabol** [lorisleiva/laravel-deployer#114]
How to unlock a 'failed' deployment

I had a deployment that did not complete so there is a lock and on subsequent deployment I get the following message:

In lock.php line 19:

  Deploy locked.
  Execute "dep deploy:unlock " to unlock.

dep deploy:unlock
  There are no commands defined in the "deploy" namespace.

php artisan deploy:unlock does not exists

**Comment by rabol** [comment]
a workaround is this:

vendor/bin/dep --file=vendor/lorisleiva/laravel-deployer/.build/deploy.php deploy:unlock

**Comment by lorisleiva** [comment]
https://github.com/lorisleiva/laravel-deployer/issues/10#issuecomment-381318196
