### ISSUE TITLE
fatal: Could not read from remote repository

### ISSUE THREAD

**Issue by picbenoit** [lorisleiva/laravel-deployer#121]
Hi everybody,

I try to use laravel-deployer for my project but after a lot of tries I didn't success.
The scripts cannot execute the git clone task with the following errors : 

```
[production] < Permission denied (publickey).
[production] < fatal: Could not read from remote repository.
[production] < Please make sure you have the correct access rights
```

I am disappointed cause I add my key and my server key to gitlab and I can successfully clone my project from my PC and my server too.

Here is my deploy.php :

```

    'options' => [
        'application' => env('APP_NAME', 'Laravel'),
        'repository' => 'git@gitlab.com:xxxxxx/xxxxxx.git',
        'ssh_multiplexing' => false,
        'bin/composer' => '~/composer/composer.phar'
    ],

    /*
    |--------------------------------------------------------------------------
    | Hosts
    |--------------------------------------------------------------------------
    |
    | Here, you can define any domain or subdomain you want to deploy to.
    | You can provide them with roles and stages to filter them during
    | deployment. Read more about how to configure them in the docs.
    |
    */

    'hosts' => [
         'production' => [
            'hostname' => 'xxxxxxxxxxxxxxxxxxxxxxx',
            'deploy_path' => 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
            'user' => 'xxxxxxxxxxxx',
            'identityFile' => '~/.ssh/id_ed25519',
            'branch' => 'master',
        ],
    ],

```

Thanks for your help,

Ben

**Comment by lorisleiva** [comment]
Hi there 👋 

Have you tried without turning SSH multiplexing off?

**Comment by picbenoit** [comment]
Hi @lorisleiva,

If multiplexing is on tasks stop at the beginning because (I think) I'm on windows.

Is anyone has a deploy config file to share that is running on Windows ?

Ben

**Comment by picbenoit** [comment]
I find the solution with this post :

https://github.com/lorisleiva/laravel-deployer/issues/103

I create a read repo token in gitlab and add it to my url repo and that's working.

Url look like : https://{user}:{token}@gitlab.com/{repo}/{project}.git

**Comment by lorisleiva** [comment]
Awesome, thanks for sharing your answer.
