### ISSUE TITLE
New version error

### ISSUE THREAD

**Issue by bsormagec** [lorisleiva/laravel-deployer#125]
The command "cd /var/www/xxxxxxx/releases/74 && (setfacl -L -R -m u:"nginx           xxxxxxx":rwX -m u:`whoami`:rwX bootstrap/cache)" failed.

  Exit Code: 2 (Misuse of shell builtins)

returning this error after deployer update.

**Comment by steveerg** [comment]
I'm facing the same problem

cd ~/httpdocs/releases/1 && (setfacl -L -R -m u:"rey4D60?":rwX -m u:`whoami`:rwX bootstrap/cache)

**Comment by steveerg** [comment]
Check your deploy.php and add to your host settings the http user array key as following:
`'http_user' => '<your user>' `
Hope it helps.
