### ISSUE TITLE
How can I add set('http_user', 'esfahan') through config/deploy.php?

### ISSUE THREAD

**Issue by Daniyal-Javani** [lorisleiva/laravel-deployer#127]
Is there anyway to add `set('http_user', 'esfahanaha');` through the `config/deploy.php`?

I tried `'http_user' => 'esfahanaha',` in `config/deploy.php` but it doesn't worked.

**Comment by fgilio** [comment]
There's an `options` key in the Deployment options section, did you try there?

**Comment by Daniyal-Javani** [comment]
Thanks, it worked

**Comment by fgilio** [comment]
Glad it worked!
