### ISSUE TITLE
mkdir: cannot create directory '/var/www/example.com': Permission denied

### ISSUE THREAD

**Issue by nighon** [lorisleiva/laravel-deployer#132]
Hello! When I run `php artisan deploy -vvv`, I encountered a problem:
`mkdir: cannot create directory '/var/www/example.com': Permission denied`

Below is my config file, please note that I used user "ubuntu" to login to my server, it has sudo privilege.

```
    # config/deploy.php
    'hosts' => [
        'example.com' => [
            'deploy_path' => '/var/www/example.com',
            'user' => 'ubuntu',
        ],
    ],
```

**Comment by nighon** [comment]
What I expect are:
1. login via user `ubuntu`
2. then `sudo mkdir /var/www/example.com`, and `chown www-data:www-data /var/www/example.com
3. upload files to `/var/www/example.com`

I am not sure is these are steps are supported? Or it is recommended to login via root?

**Comment by lorisleiva** [comment]
Hi there 👋 

It looks like this is an issue with your `writable_mode` configuration.

https://deployer.org/docs/configuration.html#writable_mode

I hope this helps.

**Comment by nighon** [comment]
Thanks for your guide! Now I know how it works:

1. sudo chown -R ubuntu:ubuntu /var/www/example.com
2. then in my local computer: php artisan deploy -s firstdeploy -o git_tty=true
