### ISSUE TITLE
[Idea] Copy node_modules and vendor directories if lock-files hasn't changed

### ISSUE THREAD

**Issue by adevade** [lorisleiva/laravel-deployer#137]
Wouldn't it be safe to assume that if the `package-lock.json` and `composer.lock` files hasn't changed since the last release, you can just copy the `node_modules` and `vendor` directories to the current release?

There's probably something I'm missing that's not ideal with this solution or maybe the issue should go in the [deployer repo](https://github.com/deployphp/deployer), but I just thought I'd throw it out there.

Thanks for a great package!

**Comment by lorisleiva** [comment]
Hi there 👋 

Yes, that's absolutely possible but the gain in performance will not really be worth the added complexity for the following reasons.

**Regarding `composer`.** If the dependencies haven't changed, they will all be cached and running `composer install` will be very fast and essentially equivalent to running a `cp` command.

**Regarding `npm`.** If there is already a previous release, its `node_modules` will be copied prior to running `npm install`. Thus, it greatly increases the speed of the command when updating a subset of its dependencies. Furthermore, if the dependencies haven't changed at all, `npm install` will simply not run. Which is again equivalent to what you suggested. Here is the code for the [`npm install` task](https://github.com/deployphp/recipes/blob/4dcbee50717717333297084f339cd103aa6b6a77/recipe/npm.php):

```php
desc('Install npm packages');
task('npm:install', function () {
    if (has('previous_release')) {
        if (test('[ -d {{previous_release}}/node_modules ]')) {
            run('cp -R {{previous_release}}/node_modules {{release_path}}');
            
            // If package.json is unmodified, then skip running `npm install`
            if (!run('diff {{previous_release}}/package.json {{release_path}}/package.json')) {
                return;
            }
        }
    }
    run("cd {{release_path}} && {{bin/npm}} install");
});
```

In any case, I thank you for your suggestion and I hope my answer was useful. 🍀

**Comment by adevade** [comment]
@lorisleiva Beautiful!! Very good answer! Thank you!
