### ISSUE TITLE
rsync exclude options is pattern, not folder

### ISSUE THREAD

**Issue by dostrog** [lorisleiva/laravel-deployer#14]
To avoid excluding subfolders with name 'vendor', for example generated `../public/css/vendor/vendor.css` etc and exclude only roots `/vendor` it is good to change rsync default options in local strategy from

```
// config/deploy.php

'options' => [
    'local_upload_options' => [
        'options' => [ 
            '--exclude=.git',
            '--exclude=vendor',
            '--exclude=node_modules',
        ],
    ],
],

```
to

```
// config/deploy.php

'options' => [
    'local_upload_options' => [
        'options' => [ 
            '--exclude=.git',
            '—exclude=/vendor',
            '--exclude=node_modules',
        ],
    ],
],
```

**Comment by lorisleiva** [comment]
Good to know thanks. Any particular reasons you only prefixed the `vendor` folder or should I prefix all three whilst I’m at it?

**Comment by dostrog** [comment]
"vendor" is word for things like `public/css/vendor`, `public/js/vendor`… which used very often so using `/vendor` (in root to exclude composer packages) and leave vendor from subfolders is more right way I suppose.

Including `.git` and/or `node_modules` to production is not good idea so your variant for these folders IMHO good.

_P.S. Sorry for my English and thanks for your work!_

**Comment by lorisleiva** [comment]
I've made those changes, thanks for you help!
