### ISSUE TITLE
Using SSHGate with Laravel Deployer

### ISSUE THREAD

**Issue by manoaratefy** [lorisleiva/laravel-deployer#141]
Good morning,

I'm using [SSHGate](https://github.com/Tauop/sshGate) to access to my LXC instances (10.x.x.x) from Internet. The SSH connection command is like this:

`ssh sshgate@mysshproxyserver.com 10.x.x.x`

So, if I need to do, for example `uptime` on `10.x.x.x`, I will do that:

`ssh sshgate@mysshproxyserver.com 10.x.x.x uptime`

Of course, key based authentication is used.

Is there a way to setup this kind of SSH connection on Laravel Deployer?

**Comment by lorisleiva** [comment]
Hi there 👋 

I'm afraid I'm not 100% sure but I don't think so. 

Laravel Deployer is based on [DeployerPHP](https://github.com/deployphp/deployer) which defines hosts using a username and an IP/domain.

There are quite a few SSH configurations available so there might be a way to sort something out with those.

- [Documentation on SSH configuration from Laravel Deployer](https://github.com/lorisleiva/laravel-deployer/blob/2215d04d9193b8fbe2adc0a9d6c00ecb1922fd59/docs/overview-configure-hosts.md#authentication)
- [Documentation on SSH configuration from DeployerPHP](https://deployer.org/docs/hosts.html). Note that anything available in DeployerPHP should be available in Laravel Deployer. Let me know if you need any help translating from one to the other.

I hope this helps. 🍀
