### ISSUE TITLE
[Docuentation] Installing for Lumen (6.0)

### ISSUE THREAD

**Issue by samo9789** [lorisleiva/laravel-deployer#143]
Hi,

This is a remark on your documentation more than an issue but I had to edit `bootstrap/app.php` in Lumen to add  : 

```
$app->register(Lorisleiva\LaravelDeployer\LaravelDeployerServiceProvider::class);
```
 otherwise the php artisan deploy:init command was missing, I would get the error : 

> There are no commands defined in the "deploy" namespace.

Thanks for the package, deployer is great.

**Comment by lorisleiva** [comment]
Hi there 👋 

Thanks for reporting this. I've updated the documentation in 31e7bb22379d9f657af53df43f34d813123a234d.
