### ISSUE TITLE
Laravel Queues with Deployer

### ISSUE THREAD

**Issue by efraim14** [lorisleiva/laravel-deployer#144]
Hello,

i have been using this tutorial https://lorisleiva.com/laravel-deployment-using-gitlab-pipelines/ to achieve CI/CD with laravel deployer into my Ubuntu VM.

My application using Laravel queue and i use supervisor to keep the queue worker running on my VM. I'm using `php artisan queue:work` to process all the queues.

One of my problem is, i have to keep restart my supervisor every time i deploy my application. The issue related is on here: https://stackoverflow.com/questions/30306954/does-supervisord-process-need-restart-after-changes-to-laravel-file

How can i run `supervisorctl reload` every time i make a deployment? can i add this to config/deploy.php ?

**Comment by pmochine** [comment]
Good question, I'm also starting to deploy to my staging page, so I'm in the learning phase right now. However, what helped me is to use Laravel Horizon. 

If you read this: https://github.com/lorisleiva/laravel-deployer/issues/34 or that https://github.com/lorisleiva/laravel-deployer/issues/54

You will read that you don't need to reload supervisor but instead you just need to terminate horizon. 

Please correct me if I'm wrong

**Comment by lorisleiva** [comment]
Hi there 👋 

That is correct. If you're using Horizon and you've got a deamon process on your host that runs `php artisan horizon` (see screenshot below for example with Laravel Forge), then the `artisan:horizon:terminate` task will gracefully restart horizon on each deployment.

<img width="1054" alt="Screenshot 2019-10-15 at 16 41 01" src="https://user-images.githubusercontent.com/3642397/66847068-ad9f9780-ef6a-11e9-9225-cead1f0b48a1.png">

Now, if you're not using Horizon but a "custom" worker supervisor, you might have to create your own deployment task for this.

For example, a task that simply runs `supervisorctl reload` on your host could be defined like this.

```php
<?php

namespace Deployer;

desc('Reload supervisor');
task('supervisor:reload', function () {
    run("cd {{release_path}} && supervisorctl reload");
});
```

For more information, on how to create and use your own tasks, please [refer to the documentation](https://github.com/lorisleiva/laravel-deployer/blob/31e7bb22379d9f657af53df43f34d813123a234d/docs/how-to-custom-recipes.md).

I hope this helps. 🍀

**Comment by efraim14** [comment]
@lorisleiva thank you for your code, it's working and the deployer reload my supervisor for every deployment. Some of my applications doesn't use Redis as the queue connection so i haven't tried laravel horizon.

Thanks for your help!

**Comment by AsterYujano** [comment]
Hello,
I got the same error :) 

In the case you use a `deploy` user for your deployment, you can run into `permission issues` as supervisor needs to be run as root per default.

Those steps solve the permission problem:
```bash
groupadd supervisor
usermod -a -G supervisor deploy

vi /etc/supervisor/supervisord.conf
```

Change this part:
```yaml
[unix_http_server]
file=/var/run/supervisor.sock   ; (the path to the socket file)
chmod=0770                            ; writeable by owner and group, socket file mode (default 0700)
chown=root:supervisor
```
```
supervisorctl reload
```

Try to log again with deploy user, and run `supervisorctl reload` to check if the permissions are right now.

Source: https://github.com/Supervisor/supervisor/issues/173#issuecomment-186128727

Best,

**Comment by 3li3bdalla** [comment]
@AsterYujano  You have wonderful solution her  , But i think you do need to add the root user to the supervisor group also right ? 
```
usermod -a -G supervisor  root
```
