### ISSUE TITLE
composer_action option seems incorrect/unused

### ISSUE THREAD

**Issue by ragingdave** [lorisleiva/laravel-deployer#145]
In looking to configure a staging type build which includes all dev and regular dependencies, it seems that composer_action is not just unused but completely unreferenced from any code? The actual call that hits composer for the vendor task ends up only using the `bin/composer` and `composer_options`? Is this correct or am I missing something?

**Comment by lorisleiva** [comment]
Hi there 👋 

Yes, this is correct.

`composer_action` is only used within `composer_options` ([see documentation](https://github.com/lorisleiva/laravel-deployer/blob/31e7bb22379d9f657af53df43f34d813123a234d/docs/all-options.md)):

<img width="914" alt="Screenshot 2019-10-15 at 16 46 50" src="https://user-images.githubusercontent.com/3642397/66847586-8d240d00-ef6b-11e9-8ad1-c0fda7d03713.png">

**Comment by ragingdave** [comment]
Ah I see, I thought the docs were wrong and perhaps those 2 were independently configurable, but in overriding composer_options, you basically negate any usage of composer_action unless you specifically keep that part in place.

Thanks for the clarity!
