### ISSUE TITLE
Add more artisan tasks

### ISSUE THREAD

**Issue by neolikotsi** [lorisleiva/laravel-deployer#146]
Add more tasks to the `lorisleiva/laravel-deployer/src/task/artisan.php` list. These tasks are part of the `deployer/deployer` package,  defined in  `deployer/deployer/recipe/laravel.php`

1. `artisan:event:clear`
2. `artisan:event:cache`
3. `artisan:view:cache`

Will do a pull request for this issue

**Comment by lorisleiva** [comment]
Go for it! Thanks for opening this issue 👍
