### ISSUE TITLE
env('APP_NAME') returning null

### ISSUE THREAD

**Issue by JFunu** [lorisleiva/laravel-deployer#151]
Hello, I have a little problem after deploying. calling `env('APP_NAME')` returns null. calling `env()` in my code returns null. I use the `basic` deploy strategy.
The deployment succeeds but code that uses `env('KEY')` no longer works.
Any help will be much appreciated

**Comment by lorisleiva** [comment]
Hi there 👋 

That is to be expected. The `env()` function will always return `null` when the configuration is cached. 

So you can either:
- Replace all your loose `env()` calls by `config()` calls and only use `env` within config files. _(recommended)_
- **Or** not cache it at all (i.e. remove the `artisan:config:cache` from your deployment process)

See official Laravel documentation:

<img width="749" alt="Screenshot 2019-03-25 at 12 04 53" src="https://user-images.githubusercontent.com/3642397/54918509-5b2b5a80-4ef6-11e9-9e85-39de731774da.png">
