### ISSUE TITLE
Exit Code: 255 (Unknown error) on deploy after reseting repo

### ISSUE THREAD

**Issue by ekntrtmz** [lorisleiva/laravel-deployer#153]
Deploy fails after I have reset my repo. Before deploy was working without problems (deploy.php is identical to before reseting the repo).

I am not able to find out where the problem is. Please help.

Error message after `php artisan deploy production`

In Client.php line 103:
                                                                         
  The command "cd /var/www/laravel/releases/1 && /usr/bin/php /usr/loc  
  al/bin/composer install --verbose --prefer-dist --no-progress --no-in  
  teraction --no-dev --optimize-autoloader --no-suggest" failed.         
                                                                         
  Exit Code: 255 (Unknown error)                                         
                                                                         
  Host Name: some.domain                                                    
                                                                         
  ================                                                       
  Loading composer repositories with package information                 
  Installing dependencies from lock file                                 
  Dependency resolution completed in 0.000 seconds                       
  Analyzed 111 packages to resolve dependencies                          
  Analyzed 257 rules to resolve dependencies                             
  Package operations: 54 installs, 0 updates, 0 removals                 
  Installs: psr/container:1.0.0, symfony/service-contracts:v2.0.1, symf  
  ony/polyfill-php73:v1.13.1, symfony/polyfill-mbstring:v1.13.1, symfon  
  y/console:v4.4.1, deployer/phar-update:v2.1.0, doctrine/inflector:1.3  
  .1, doctrine/lexer:1.2.0, dragonmantank/cron-expression:v2.3.0, eruse  
  v/parsedown:1.7.3, symfony/polyfill-ctype:v1.13.1, phpoption/phpoptio  
  n:1.6.0, vlucas/phpdotenv:v3.6.0, symfony/css-selector:v5.0.1, tijsve  
  rkoyen/css-to-inline-styles:2.2.2, symfony/polyfill-php72:v1.13.1, sy  
  mfony/var-dumper:v4.4.1, symfony/routing:v4.4.1, symfony/process:v4.4  
  .1, symfony/polyfill-intl-idn:v1.13.1, symfony/mime:v5.0.1, symfony/h  
  ttp-foundation:v4.4.1, symfony/event-dispatcher-contracts:v1.1.7, sym  
  fony/event-dispatcher:v4.4.1, psr/log:1.1.2, symfony/debug:v4.4.1, sy  
  mfony/error-handler:v4.4.1, symfony/http-kernel:v4.4.1, symfony/finde  
  r:v4.4.1, symfony/polyfill-iconv:v1.13.1, egulias/email-validator:2.1  
  .11, swiftmailer/swiftmailer:v6.2.3, paragonie/random_compat:v9.99.99  
  , ramsey/uuid:3.9.1, psr/simple-cache:1.0.1, opis/closure:3.5.1, symf  
  ony/translation-contracts:v2.0.1, symfony/translation:v4.4.1, nesbot/  
  carbon:2.27.0, monolog/monolog:2.0.1, league/flysystem:1.0.57, larave  
  l/framework:v6.6.1, fideloper/proxy:4.2.1, jakub-onderka/php-console-  
  color:v0.2, nikic/php-parser:v4.3.0, jakub-onderka/php-console-highli  
  ghter:v0.4, dnoegel/php-xdg-base-dir:0.1, psy/psysh:v0.9.11, laravel/  
  tinker:v2.0.0, deployer/recipes:6.2.2, symfony/yaml:v4.4.1, pimple/pi  
  mple:v3.2.3, deployer/deployer:v6.6.0, lorisleiva/laravel-deployer:v0  
  .2.16                                                                  
    - Installing psr/container (1.0.0): Loading from cache               
   Extracting archive  - Installing symfony/service-contracts (v2.0.1):  
   Loading from cache                                                    
   Extracting archive  - Installing symfony/polyfill-php73 (v1.13.1): L  
  oading from cache                                                      
   Extracting archive  - Installing symfony/polyfill-mbstring (v1.13.1)  
  : Loading from cache                                                   
   Extracting archive  - Installing symfony/console (v4.4.1): Loading f  
  rom cache                                                              
   Extracting archive  - Installing deployer/phar-update (v2.1.0): Load  
  ing from cache                                                         
   Extracting archive  - Installing doctrine/inflector (1.3.1): Loading  
   from cache                                                            
   Extracting archive  - Installing doctrine/lexer (1.2.0): Loading fro  
  m cache                                                                
   Extracting archive  - Installing dragonmantank/cron-expression (v2.3  
  .0): Loading from cache                                                
   Extracting archive  - Installing erusev/parsedown (1.7.3): Loading f  
  rom cache                                                              
   Extracting archive  - Installing symfony/polyfill-ctype (v1.13.1): L  
  oading from cache                                                      
   Extracting archive  - Installing phpoption/phpoption (1.6.0): Loadin  
  g from cache                                                           
   Extracting archive  - Installing vlucas/phpdotenv (v3.6.0): Loading   
  from cache                                                             
   Extracting archive  - Installing symfony/css-selector (v5.0.1): Load  
  ing from cache                                                         
   Extracting archive  - Installing tijsverkoyen/css-to-inline-styles (  
  2.2.2): Loading from cache                                             
   Extracting archive  - Installing symfony/polyfill-php72 (v1.13.1): L  
  oading from cache                                                      
   Extracting archive  - Installing symfony/var-dumper (v4.4.1): Loadin  
  g from cache                                                           
   Extracting archive  - Installing symfony/routing (v4.4.1): Loading f  
  rom cache                                                              
   Extracting archive  - Installing symfony/process (v4.4.1): Loading f  
  rom cache                                                              
   Extracting archive  - Installing symfony/polyfill-intl-idn (v1.13.1)  
  : Loading from cache                                                   
   Extracting archive  - Installing symfony/mime (v5.0.1): Loading from  
   cache                                                                 
   Extracting archive  - Installing symfony/http-foundation (v4.4.1): L  
  oading from cache                                                      
   Extracting archive  - Installing symfony/event-dispatcher-contracts   
  (v1.1.7): Loading from cache                                           
   Extracting archive  - Installing symfony/event-dispatcher (v4.4.1):   
  Loading from cache                                                     
   Extracting archive  - Installing psr/log (1.1.2): Loading from cache  
   Extracting archive  - Installing symfony/debug (v4.4.1): Loading fro  
  m cache                                                                
   Extracting archive  - Installing symfony/error-handler (v4.4.1): Loa  
  ding from cache                                                        
   Extracting archive  - Installing symfony/http-kernel (v4.4.1): Loadi  
  ng from cache                                                          
   Extracting archive  - Installing symfony/finder (v4.4.1): Loading fr  
  om cache                                                               
   Extracting archive  - Installing symfony/polyfill-iconv (v1.13.1): L  
  oading from cache                                                      
   Extracting archive  - Installing egulias/email-validator (2.1.11): L  
  oading from cache                                                      
   Extracting archive  - Installing swiftmailer/swiftmailer (v6.2.3): L  
  oading from cache                                                      
   Extracting archive  - Installing paragonie/random_compat (v9.99.99):  
   Loading from cache                                                    
   Extracting archive  - Installing ramsey/uuid (3.9.1): Loading from c  
  ache                                                                   
   Extracting archive  - Installing psr/simple-cache (1.0.1): Loading f  
  rom cache                                                              
   Extracting archive  - Installing opis/closure (3.5.1): Loading from   
  cache                                                                  
   Extracting archive  - Installing symfony/translation-contracts (v2.0  
  .1): Loading from cache                                                
   Extracting archive  - Installing symfony/translation (v4.4.1): Loadi  
  ng from cache                                                          
   Extracting archive  - Installing nesbot/carbon (2.27.0): Loading fro  
  m cache                                                                
   Extracting archive  - Installing monolog/monolog (2.0.1): Loading fr  
  om cache                                                               
   Extracting archive  - Installing league/flysystem (1.0.57): Loading   
  from cache                                                             
   Extracting archive  - Installing laravel/framework (v6.6.1): Loading  
   from cache                                                            
   Extracting archive  - Installing fideloper/proxy (4.2.1): Loading fr  
  om cache                                                               
   Extracting archive  - Installing jakub-onderka/php-console-color (v0  
  .2): Loading from cache                                                
   Extracting archive  - Installing nikic/php-parser (v4.3.0): Loading   
  from cache                                                             
   Extracting archive  - Installing jakub-onderka/php-console-highlight  
  er (v0.4): Loading from cache                                          
   Extracting archive  - Installing dnoegel/php-xdg-base-dir (0.1): Loa  
  ding from cache                                                        
   Extracting archive  - Installing psy/psysh (v0.9.11): Loading from c  
  ache                                                                   
   Extracting archive  - Installing laravel/tinker (v2.0.0): Loading fr  
  om cache                                                               
   Extracting archive  - Installing deployer/recipes (6.2.2): Loading f  
  rom cache                                                              
   Extracting archive  - Installing symfony/yaml (v4.4.1): Loading from  
   cache                                                                 
   Extracting archive  - Installing pimple/pimple (v3.2.3): Loading fro  
  m cache                                                                
   Extracting archive  - Installing deployer/deployer (v6.6.0): Loading  
   from cache                                                            
   Extracting archive  - Installing lorisleiva/laravel-deployer (v0.2.1  
  6): Loading from cache                                                 
   Extracting archiveGenerating optimized autoload files                 
  > post-autoload-dump: Illuminate\Foundation\ComposerScripts::postAuto  
  loadDump                                                               
  > post-autoload-dump: @php artisan package:discover --ansi             
  PHP Fatal error:  Class 'Laravel\Telescope\TelescopeApplicationServic  
  eProvider' not found in /var/www/some.domain/releases/1/app/Providers/Te  
  lescopeServiceProvider.php on line 10                                  
  Script @php artisan package:discover --ansi handling the post-autoloa  
  d-dump event returned with error code 255

**Comment by ekntrtmz** [comment]
and here the second part of the error message:

   Symfony\Component\Process\Exception\ProcessFailedException  : The command "vendor/bin/dep --file=vendor/lorisleiva/laravel-deployer/.build/deploy.php deploy production" failed.

Exit Code: 255(Unknown error)

Working directory:

Output:
================


Error Output:
================


  at /home/dev/vendor/symfony/process/Process.php:254
    250|      */
    251|     public function mustRun(callable $callback = null, array $env = []): self
    252|     {
    253|         if (0 !== $this->run($callback, $env)) {
  > 254|             throw new ProcessFailedException($this);
    255|         }
    256| 
    257|         return $this;
    258|     }

  Exception trace:

  1   Symfony\Component\Process\Process::mustRun(Object(Closure))
      /home/dev/vendor/lorisleiva/laravel-deployer/src/LaravelDeployer/Commands/BaseCommand.php:110

  2   Lorisleiva\LaravelDeployer\Commands\BaseCommand::process("vendor/bin/dep --file=vendor/lorisleiva/laravel-deployer/.build/deploy.php deploy production")
      /home/dev/vendor/lorisleiva/laravel-deployer/src/LaravelDeployer/Commands/BaseCommand.php:58

**Comment by ekntrtmz** [comment]
After trying to deploy my Repo with `dep deploy` I found out that it might have to do with this issue:
https://github.com/deployphp/deployer/issues/1850

It seems like artisan:optimize is not suited to work with the laravel boilerplate which is using closures in routes. Either remove closures or overwrite the artisan:optimize command solved it for me.

**Comment by VivekShingala** [comment]
Hi @ekntrtmz 

Could you please tell how did you fix it?

**Comment by nullwriter** [comment]
@ekntrtmz how did you fix?

**Comment by ekntrtmz** [comment]
@nullwriter @VivekShingala 
As the error message tells, it was related to Telescope Service Provider not being found. 
I had to adjust my composer.json
