### ISSUE TITLE
Please provide a valid cache path

### ISSUE THREAD

**Issue by RosiersRobin** [lorisleiva/laravel-deployer#157]
I tried alot of things already which I will describe here...

I currently get the follwoing error:

![Error](https://i.imgur.com/5oQRWPG.png)

(think the `--vvv `away)

So I just run on a pileple (that I never changed) te command `php artisan deploy staging`, however, all of a sudden the deployment doesn't work anymore.... I do have the correct files in my storage folder, I did try to clear the cache, I even restarted my server multiple times. Nothing works. I have this on my staging environment and on my production env....

I have the following packages installed:

```
root@fe5e668e83af:/phpapp# php artisan package:discover --ansi
Discovered Package: barryvdh/laravel-debugbar
Discovered Package: benjamincrozat/laravel-dropbox-driver
Discovered Package: beyondcode/laravel-dump-server
Discovered Package: beyondcode/laravel-mailbox
Discovered Package: cviebrock/eloquent-sluggable
Discovered Package: fideloper/proxy
Discovered Package: intervention/image
Discovered Package: it-brains/queue-job-logger
Discovered Package: laravel/tinker
Discovered Package: lorisleiva/laravel-deployer
Discovered Package: maatwebsite/excel
Discovered Package: nesbot/carbon
Discovered Package: nunomaduro/collision
Discovered Package: nunomaduro/larastan
Discovered Package: spatie/laravel-analytics
Discovered Package: spatie/laravel-backup
Discovered Package: spatie/laravel-cookie-consent
Discovered Package: spatie/laravel-honeypot
Discovered Package: spatie/laravel-image-optimizer
Discovered Package: spatie/laravel-medialibrary
Discovered Package: spatie/laravel-permission
Discovered Package: spatie/laravel-responsecache
Discovered Package: spatie/laravel-sitemap
Discovered Package: yoeunes/toastr
Package manifest generated successfully.
```

I never changed something to my deployments and/or on the production server (on which it also throws the same error) Anyone who has an idea?

**Comment by lorisleiva** [comment]
Hi there 👋 

I'm afraid I've never run into this issue before so I'm not sure what is going on. I'll leave this open in case someone else can help.

**Comment by RosiersRobin** [comment]
Hi so apparently it was an cache issue.... (I hate my life haha) I've spend like 3 days trying to fix this and then I cleared my runners cache and it worked... So if anyone encounters this issue, CACHE HATES YOU :P

**Comment by hell-n** [comment]
Hello!

I'm having the same issue. I'm suspecting that I ruined the cache by canceling the deployment.
Since I'm farilry unfamiliar with this project... What exactly is the "runners cache" and how am I supposed to clear it?

**Comment by shankhadevpadam** [comment]
@RosiersRobin how to clear runners cache.

**Comment by RosiersRobin** [comment]
> @RosiersRobin how to clear runners cache.

https://stackoverflow.com/a/48509094/4371664
