### ISSUE TITLE
Branch name on deployment

### ISSUE THREAD

**Issue by pixelplant** [lorisleiva/laravel-deployer#159]
Not necessarily an issue but mostly a question or feature request if it does not exist.
How would we go about when we want to deploy features to dynamic subdomains? How do we have access to the current branch name in the deploy.php config?

I tried this but it does not work
```
        'test-domain.blabla.com' => [
            'deploy_path' => '/var/www/html/feature/{{branch}}',
            'user'        => 'root',
            'stage'       => 'feature'
        ]
```

Is the current git branch name being deployed exposed in a variable that we could insert in the deploy path?

Thank you

**Comment by pixelplant** [comment]
The question is mostly about how can we grab the current branch we're deploying and use it inside the deploy.php file.
We're using gitlab for ci/cd so we can easily access the current branch in a variable called ${CI_COMMIT_REF_SLUG}

We just need to pass this on to the "php artisan deploy" command either as a console parameter, or if deployer already grabs it we need to know the name of the variable that we could use inside deploy.php

**Comment by lorisleiva** [comment]
Hi there 👋

Sorry for the long reply. I'm not 100% sure about this, to be honest, but I _think_ there might be a way to do this.

The reason the option below does not work is that the `{{branch}}` variable has not been set to Deployer.

```php
'deploy_path' => '/var/www/html/feature/{{branch}}',
```

If within your CI/CD environment you have access to that branch name as `CI_COMMIT_REF_SLUG`, then you might be able to achieve what you want by running something like that.

```sh
php artisan deploy --branch="$(echo $CI_COMMIT_REF_SLUG)"
```

I hope this helps. Let me know how you get on. 🍀

**Comment by pixelplant** [comment]
@lorisleiva thanks. almost completed the process, once it's done i'll share the gitlab config I used and the deploy config and recipe. I am just a bit stuck on the .env update part. Since I'm creating dynamic deploys I also want to create a database copy for each deploy. Is there any command in the deployer package that allows you to easily update values in your .env file? like $deployer->updateEnv('DB_DATABASE', 'my_value') or can I only rely on linux commands to update the file?

**Comment by lorisleiva** [comment]
Hi there 👋 

Unfortunately not but this is a good idea for a PR 🙂 

Something like `php artisan deploy:update_env DB_DATABASE 'my_value'` could be cool.

**Comment by pixelplant** [comment]
@lorisleiva I finally did it using the "sed" linux command, something like:
`        run("cd {{deploy_path}}/current && sed -i 's/DB_DATABASE=neho_local_db/DB_DATABASE=dev_$branch/g' .env");
        run("cd {{deploy_path}}/current && sed -i 's/APP_URL=http:\/\/neho.local/APP_URL=http:\/\/$branch.my_custom.domain/g' .env");
        run("cd {{deploy_path}}/current && sed -i 's/APP_DOMAIN=neho.local/APP_DOMAIN=$branch.my_custom.domain/g' .env");`

This works because I use a predefined .env file where I can replace already hardcoded values (like neho.local or neho_local_db with the dynamic ones coming from the branch.

How can I access gitlab variables inside my deployer recipe? I have access to them inside my .gitlab-ci.yml but can I easily access them in my recipe? Since I'm doing the db creation and sync I'd love to define the DB password and other parameters like the db user and host directly inside gitlab and not in my recipe file.

**Comment by pixelplant** [comment]
@lorisleiva Ok, so I've managed to finally make it work.

The idea is that we have multiple branches, one for each ticket and they get names like "feature/j321-my-ticket-name" (this would be linked to a ticket with the number 321 inside our ticketing application)
The CI/CD passes through gitlab's own service so we wanted that every time we do a commit on one of these features that a deploy was done on one of our custom domains so that tickets can get tested easily without interfering with other tickets. Before we used to merge a lot of tickets on staging and test them, but as the project grew we had lots of conflicts or tickets that did various changes on the same functionality so the easiest was to create separate deploys for each branch so that we can test them in isolation.

To make this work, we have setup a custom domain, let's call it mytests.com and we wanted that each deploy would create a subdomain with the branch name on this domain. So for a branch called "_feature/j132-login-page_" and "_feature/j270-remove-contact-page_" this will create 2 separate deploiments on **j132-login-page.mytests.com** and **j270-remove-contact-page.mytests.com** respectively where these 2 tickets can be tested in isolation.

In order for this to work we need to setup 2 things initially. Our web server, to accept dynamic subdomains (in our case we use nginx) and the gitlab config in gitlab-cy.yml so that we trigger this dinamic deploy.

This is the nginx config for mytests.com so that it supports dynamic subdomains. All our deploiments will be stored inside "/var/www/feature/". The most important part is the "server_name" and "root" part.
```
server {
    listen 80;

    server_name ~^(?<subdomain>.+)\.mytests\.com$ ;
    root /var/www/feature/$subdomain/current/public;
    index index.html index.html index.php;

    charset utf-8;

    client_max_body_size 20M;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
            try_files $uri /index.php =404;
            fastcgi_split_path_info ^(.+\.php)(/.+)$;
            fastcgi_pass unix:/run/php/php7.3-fpm.sock;
            fastcgi_index index.php;
            fastcgi_read_timeout 120;
            include fastcgi_params;
            fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
            fastcgi_param DOCUMENT_ROOT $realpath_root;
    }

    location ~ /\.(?!well-known).* {
        deny all;
    }
```
In order for all of this to work you also need to add a CNAME record for your domain that maps all subdomain requests to your main domain. The line in red in the below image:
![image](https://user-images.githubusercontent.com/492082/77519641-1d9e3c00-6e80-11ea-87c0-e491f5e7d1ea.png)

Here is the config to do inside .gitlab_ci.yml:
We have 3 stages defined:
```
stages:
  - build
  - test
  - deploy
```
and the config for the dynamic deploy is this one, it's run on the "deploy" stage:
```
dynamic_feature:
  stage: deploy

  script:
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan -H mytests.com >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - find . -type f -not -path "./vendor/*" -exec chmod 664 {} \;
    - find . -type d -not -path "./vendor/*" -exec chmod 775 {} \;
    - php artisan deploy feature -s dynamic_feature --branch=$(echo $CI_COMMIT_REF_NAME)

  environment:
    name: feature
    url: http://${CI_COMMIT_REF_SLUG}.mytests.com/
  except:
    - master,develop,staging
```

So as you can see we run an artisan deploy with the "dynamic_feature" strategy.
The strategy, to be placed inside your deploy.php file, looks like this:
```
        // specific strategy for dynamic features
        'dynamic_feature'      => [
            'hook:start',
            'deploy:prepare',
            'deploy:lock',
            'deploy:release',
            'deploy:update_code',
            'upload',
            'deploy:shared',
            'deploy:vendors',
            'deploy:writable',
            'hook:ready',
            'deploy:symlink',
            'db:dummy',
            'deploy:unlock',
            'cleanup',
            'horizon:restart',
            'hook:done',
        ],
```

Inside the same deploy.php we also defined the host for our custom domain:
```
        'mytests.com' => [
            'deploy_path' => '/var/www/feature/{{branch}}',  // this corresponds to the path defined in nginx
            'user'        => 'debian',
            'stage'       => 'feature'
        ]
```

All the calls are standard except for the "db:dummy" recipe, which is a custom recipe that you should place in your local recipes folder. We need this recipe only for the 1st deploy of each feature. Since we're creating new folders for each ticket, we also need to import the database so that we have a clean DB for each deploy. The said recipe takes care of this and looks like:
```
desc('Prepare a dummy DB copy');
task('db:dummy', function () {
    $releaseName = get('release_name');

    // Create the DB and import the SQL file only if this feature was never released
    if ($releaseName == '1') {
        // our branch names start with "feature/xyz" so we only use the right part of "/", the xyz part
        $branch = explode("/", str_replace('-', '_', get('branch')));
        if (sizeof($branch) > 1) {
            $branch = $branch[1];
        } else {
            $branch = $branch[0];
        }

        // we add a "dev_" prefix for our database name
        $dbName = 'dev_' . $branch;

        // we use a predefined .env file for the features that we rename during deployment
        writeln("Copying the env file");
        run('cd {{deploy_path}}/current && cp -f .env.feature {{deploy_path}}/shared/.env');
        // we write the new db name and domain url inside this .env file
        writeln("Updating DB in ENV");
        run("cd {{deploy_path}}/shared && sed -i 's/DB_DATABASE=predefined_laravel/DB_DATABASE=$dbName/g' .env");
        run("cd {{deploy_path}}/shared && sed -i 's/APP_URL=http:\/\/local.domain/APP_URL=http:\/\/$branch.mytests.com/g' .env");
        run("cd {{deploy_path}}/shared && sed -i 's/APP_DOMAIN=local.domain/APP_DOMAIN=$branch.mytests.com/g' .env");
        writeln("Regenerating artisan key");
        run('cd {{deploy_path}}/current && php artisan key:generate && php artisan config:clear');

        // If you use MySQL for your database, replace the following run command with whatever you want to do in MySQL
        // Make sure to place your sql dump file inside /tmp/dump/limit_dump.sql or update the path to where you stored this file on your server
        writeln("Preparing db sync for branch $branch on database $dbName");
        run("sudo su postgres && export PGPASSWORD=YOUR_PASSWORD_HERE && createdb $dbName -h 127.0.0.1 -U YOUR_DB_USER_HERE -O YOUR_DB_USER_HERE && psql -U YOUR_DB_USER_HERE -h 127.0.0.1 $dbName < /tmp/dump/limit_dump.sql");
        writeln("Run eventual migrations");
        run('cd {{deploy_path}}/current && php artisan migrate');
    } else {
        writeln("Release exists, skipping db sync");
    }
});
```

That's pretty much all there is to it. This allows you to run dynamic deploys of all your git branches (except for "master, develop and staging" in this case), create a database and import it during the first commit on a certain branch, and do the regular update of code on next commits. It also allows you to easily test each specific feature in your browser on a subdomain that contains the name of your feature.

If you continue to modify your nginx file so that it also server your main domain and not just the subdomains you can tell it to list all your subfolders from inside /var/www/feature so that you can easily jump to any deployed feature on it's specific subdomain.
What it looks like on our side (we only have 1 dynamic feature deployed so far, there will be hundreds in the end)
![image](https://user-images.githubusercontent.com/492082/77521096-72db4d00-6e82-11ea-8540-9cf9ed1603e4.png)

This code can be further improved by sending the final subdomain (once the release is completed) either by mail to the person that should test it, or in a slack message, if you have a channel dedicated for testers

**Comment by lorisleiva** [comment]
Wow! This is amazing! Thank you so much for sharing. This would make a great article.

I'm going to document the part on how to pass CLI environment variables to Laravel Deployer since this is not documented anywhere at the moment.

Thanks again for your thorough report. 🌷

**Comment by elhaouari-mohammed** [comment]
:heart:
