### ISSUE TITLE
The process exceeded the timeout of 300 seconds.

### ISSUE THREAD

**Issue by forPelevin** [lorisleiva/laravel-deployer#16]
Hello again!

I faced with another issue while I had been running deploy:vendors task. I got `The process "ssh -A -o ControlMaster=auto -o ControlPersist=60 -o ControlPath=~/.ssh/deployer_root@222 root@222  'bash -s; printf "[exit_code:%s]" $?;'" exceeded the timeout of 300 seconds.` error. 
I found solution to set timeout to `null` in the Deployer https://github.com/deployphp/deployer/blob/master/src/Utility/ProcessRunner.php#L27. But where I can specify the parameter?

Regards,
Vlad

**Comment by lorisleiva** [comment]
Hi there,

Could you please try to add this option in your deploy.php configuration file?

```php
'options' => [
    'default_timeout' => null,
    // ...
],
```

**Comment by forPelevin** [comment]
Hi!

Thanks a lot. This works. I didn't see the timeout option in docs https://github.com/lorisleiva/laravel-deployer/blob/master/docs/all-options.md or this mentioned in another doc?

Regards,
Vlad

**Comment by lorisleiva** [comment]
That's a good point, I've now updated the documentation. Thanks!
