### ISSUE TITLE
Scripts on rollback (PHP reload)

### ISSUE THREAD

**Issue by edwinvdpol** [lorisleiva/laravel-deployer#160]
Hi! First of all, thank you very much for this awesome package!

I am using this package for a while now, and before just now, I never needed the rollback function of this package.
Today I used the command for the first time, and I noticed that the app wasn't available.
When I deploy the app, it reloads the PHP FPM service, because of the directory change.
So this command is in my deploy 'script'.

But, when I use the rollback function, there is no option to reload PHP afterwards.
I needed to login and reload PHP manually, and everything was up and running again.

Is there some kind of (hidden) feature that allows me to execute some server commands on rollback, as I do when deploying the app?

If there isn't any, would you be interested to develop this feature? It would be very useful.

Thanks in advance!

-- Edwin

**Comment by lorisleiva** [comment]
Good point! Thanks for raising this issue. I'm on it 👍

**Comment by lorisleiva** [comment]
@edwinvdpol Okay so you should now be able to add the following hook to your config file.

```php
// After a deployment has been rolled back.
'rollback' => [
    'fpm:reload',
],
```

Would you mind trying this on your project before I tag a release by using `dev-master`? I might combine this release with the support of Laravel 7.

Thanks again for your help :)

**Comment by edwinvdpol** [comment]
No worries, thank _you_ for this! I will give it a try and get back to you with the results.

**Comment by edwinvdpol** [comment]
Working like a charm as far as I can see!

`Feb 29 17:13:03 xxxxxxx systemd[1]: Reloaded The PHP 7.2 FastCGI Process Manager.`

Thank you for your help! 👍

**Comment by lorisleiva** [comment]
Awesome, Thanks! I will create a new release by the end of the day as soon as I'm done upgrading for Laravel 7.

**Comment by edwinvdpol** [comment]
Sounds good!

**Comment by lorisleiva** [comment]
Turns out I underestimated the Laravel 7 upgrade so I've made a separate release for the `rollback` hook: [`v0.2.18`](https://github.com/lorisleiva/laravel-deployer/releases/tag/v0.2.18).
