### ISSUE TITLE
How to update shared folder with files from repo git?

### ISSUE THREAD

**Issue by GetoXs** [lorisleiva/laravel-deployer#166]
Hello,
We store a some of data in storage folder on git repository. At the same we configure it as shared folder in Laravel deployer. 
Unfortunately basic/upload strategies beside first deploy doesn't update storage files according to changes on git.
Do you know any good practises how to achieve that?
I have tried to make own strategy, but I have a problem update code with symlink of storage.

**Comment by swissbyte** [comment]
similar problem here. 
the .env file does not get updated after
`php artisan deploy dev.myhost.ch -s upload`

The .env file does not correspond to the .env file which was inside of the container which has uploaded the production ready files.

**Comment by GetoXs** [comment]
Finally I wrote my own strategy with two custom tasks:
``` 
    'strategies' => [
        'aurero_upload' => [
            'hook:start',
            'deploy:prepare',
            'deploy:lock',
            'deploy:release',
            'deploy:update_code',
            'upload',
            'deploy:shared_files',                      // Link .env files to make db migration
            'deploy:writable',
            'hook:ready',
            'deploy:shared_dirs_with_copy',             // Moved at the end of the process
            'deploy:symlink',
            'deploy:unlock',
            'cleanup',
            'hook:done',
        ],
    ],

    'include' => [
        "app/Classes/DeployShared.php"
    ],
```

And custom tasks, base from php deployer project, with overriding files
`app\Classes\DeployShared.php`
```
namespace Deployer;

desc('Creating symlinks for shared files');
task('deploy:shared_files', function () {
    $sharedPath = "{{deploy_path}}/shared";

    foreach (get('shared_files') as $file) {
        $dirname = dirname(parse($file));

        // Create dir of shared file if not existing
        if (!test("[ -d {$sharedPath}/{$dirname} ]")) {
            run("mkdir -p {$sharedPath}/{$dirname}");
        }

        // Check if shared file does not exist in shared.
        // and file exist in release
        if (!test("[ -f $sharedPath/$file ]") && test("[ -f {{release_path}}/$file ]")) {
            // Copy file in shared dir if not present
            run("cp -rv {{release_path}}/$file $sharedPath/$file");
        }

        // Remove from source.
        run("if [ -f $(echo {{release_path}}/$file) ]; then rm -rf {{release_path}}/$file; fi");

        // Ensure dir is available in release
        run("if [ ! -d $(echo {{release_path}}/$dirname) ]; then mkdir -p {{release_path}}/$dirname;fi");

        // Touch shared
        run("touch $sharedPath/$file");

        // Symlink shared dir to release dir
        run("{{bin/symlink}} $sharedPath/$file {{release_path}}/$file");
    }
});

desc('Creating symlinks for shared dirs and copy content between dirs.');
task('deploy:shared_dirs_with_copy', function () {
    $sharedPath = "{{deploy_path}}/shared";

    // Validate shared_dir, find duplicates
    foreach (get('shared_dirs') as $a) {
        foreach (get('shared_dirs') as $b) {
            if ($a !== $b && strpos(rtrim($a, '/') . '/', rtrim($b, '/') . '/') === 0) {
                throw new Exception("Can not share same dirs `$a` and `$b`.");
            }
        }
    }

    foreach (get('shared_dirs') as $dir) {
        // Check if shared dir does not exist.
        if (!test("[ -d $sharedPath/$dir ]")) {
            // Create shared dir if it does not exist.
            run("mkdir -p $sharedPath/$dir");

            // If release contains shared dir, copy that dir from release to shared.
            if (test("[ -d $(echo {{release_path}}/$dir) ]")) {
                run("cp -rv {{release_path}}/$dir $sharedPath/" . dirname(parse($dir)));
            }
        }

        // Copy chaneges from source.
        run("cp -rv {{release_path}}/$dir $sharedPath/" . dirname(parse($dir)));

        // Remove from source.
        run("rm -rf {{release_path}}/$dir");

        // Create path to shared dir in release dir if it does not exist.
        // Symlink will not create the path and will fail otherwise.
        run("mkdir -p `dirname {{release_path}}/$dir`");

        // Symlink shared dir to release dir
        run("{{bin/symlink}} $sharedPath/$dir {{release_path}}/$dir");
    }
});
```
This is not a perfect solution, so I do not want to pull it into base project, but it works in our case.

**Comment by swissbyte** [comment]
thanks. I will review it and, hopefully, can implement the same behaviour here... Its annoying, that .env settings doesnt get updated automatically!

**Comment by GetoXs** [comment]
But keep in mind that my solution override files during symlink dirs, but not during symlink files :) gl

**Comment by swissbyte** [comment]
Tested right now. And it does not work as expected. 
If i do some changes to my local .env file and then run php deploy, my remote .env file in the shared folder doesnt get updated. Of course, it gets a new timestamp, but the content is still the same as before the deployment. 

Only if i manually remove the .env file from the remote host, then the correct, local one gets uploaded correctly.

**Comment by lorisleiva** [comment]
Hi there! 👋 

By definition shared files and folders will be shared across all your deployments and therefore are independent of the content of your repository.

When deploying for the first time it will use the content of your repository if it exists, otherwise blank files and/or folders will be created for you.

If you'd like a subset of your shared folders to be updated at every deployment from the content of your repository then you'd need to create a custom task. The one you've created for that purpose seems like a good example.

Otherwise, my advice would be to update the `shared_dirs` and `shared_files` options to exclude what needs to be in sync with your repository.
