### ISSUE TITLE
How to add to an options

### ISSUE THREAD

**Issue by mehrdaad** [lorisleiva/laravel-deployer#17]
With previous version you could do: ``add('shared_dirs', ['public/uploads']);``  

What's the equivalent with config/deploy.php way?

**Comment by lorisleiva** [comment]
Unfortunately the new way does not allow you to do this yet. You'd have to copy/paste the current default value and add on top of that.

However I'd like to bring that feature back, I am just not completely satisfy with the candidate solutions.

## Option 1. A new top level configuration key.
Something like `add_options` or `append`:
```php
'options' => [ 'shared_dirs' => [...] ]      // Equivalent to set('shared_dirs', [...])
'add_options' => [ 'shared_dirs' => [...] ]  // Equivalent to add('shared_dirs', [...])
```

## Option 2. Some magic prefix on the option key.
```php
'options' => [ 'shared_dirs' => [...] ]      // Equivalent to set('shared_dirs', [...])
'options' => [ 'add:shared_dirs' => [...] ]  // Equivalent to add('shared_dirs', [...])
```
The little downside is that option keys cannot legitimately start with `add:` anymore.

What do you think? Please don't hesitate to share any other options that you might have in mind.

**Comment by mehrdaad** [comment]
>  You'd have to copy/paste the current default value and add on top of that.

I accomplished this way.  

I don't really like Option 1 since there isn't any source of truth in the config file. And there might occur some magic like behaviours this way.  

Option 2 is somehow equivalent to Option1 and is vague. What if I define ``shared_dirs`` and ``add:shared_dirs``?  there does exist some ambiguity on code again.  I believe the must be just one key for each config key. Not turning a method functionality to a an array key and let it live side by side of the main key.

I suggest exposing a method from Laravel deployer that gets the default value and the developer can add his values on top of that, for example:  

    'options' => [
        'shared_dirs' => [ getDefaultConfig('shared_dirs'), 'public/uploads']
    ]

Or maybe we could create a function like ``addToDefaultConfigs(string key, array values)``. example:  

    'options' => [
        'shared_dirs' => addToDefaultConfigs('shared_dirs', [ 'public/uploads'])
    ]

**Comment by lorisleiva** [comment]
The issue with this implementation is that Laravel cannot cache your configurations if it contains functions or calls to functions that aren't `env()`:

<img width="637" alt="screen shot 2018-06-04 at 11 37 45" src="https://user-images.githubusercontent.com/3642397/40910209-d3b44e8c-67eb-11e8-88bd-f9867e3081d0.png">

**Comment by mehrdaad** [comment]
Yeah I forgot that! So What else can we do to have both dynamicity and clearity?

**Comment by mehrdaad** [comment]
Or maybe keeping it this way is good enought. Copying an array from ``defaults.php`` for 1 time shouldn't be that hard

**Comment by lorisleiva** [comment]
That was my original thought but it's a shame to loose that functionality. Especially if in the future Laravel require different default values, by adding on top of them you don't need to worry about updating them later.

**Comment by mehrdaad** [comment]
Not a big deal, setting up deployer is a one time job.  
I think default deploy.php file creation can have those default values by itself. and user can append from there.  
And that way, we have more clarity.

**Comment by lorisleiva** [comment]
Okay then I'll close this issue for now and if this lack of feature blocks more users, we'll find a better solution 🙂

**Comment by mehrdaad** [comment]
Thank you
