### ISSUE TITLE
Add custom task

### ISSUE THREAD

**Issue by azril2018** [lorisleiva/laravel-deployer#171]
How to add new custom for example

task('artisan:ckfinder:download', function () {    
    run('cd {{release_path}} && php artisan ckfinder:download');
});

Thanks in advance.

**Comment by neolikotsi** [comment]
@azril2018  see this closed [Issue comment ](https://github.com/lorisleiva/laravel-deployer/issues/65#issuecomment-437341236)

**Comment by azril2018** [comment]
1. deploy.php
..
    'include' => [
        //
        'config/deploy_custom.php',
    ],

2. config/deploy_custom.php:
<?php

namespace Deployer;

/*
task('artisan:ckfinder:download', function () {    
    run('cd {{release_path}} && php artisan ckfinder:download');
});
*/

desc('Download ckfinder');
task('artisan:ckfinder:download', function () {
    run("cd {{release_path}} && {{bin/php}} artisan ckfinder:download");
});

3. I got this error message:
PHP Notice:  Trying to get property 'tasks' of non-object in /Users/user1/www/myapp/vendor/deployer/deployer/src/functions.php on line 160

Notice: Trying to get property 'tasks' of non-object in /Users/user1/www/myapp/vendor/deployer/deployer/src/functions.php on line 160

In functions.php line 160:
                                           
 Call to a member function set() on null

**Comment by neolikotsi** [comment]
@azril2018 share the contents of your `deploy.php` file

**Comment by azril2018** [comment]
return [
    'default' => 'basic',

    'strategies' => [
        //
    ],

    'hooks' => [
        'start' => [
            //
        ],
        
        'build' => [
            //
        ],
        
        'ready' => [
            'artisan:storage:link',
            'artisan:view:clear',
            'artisan:cache:clear',
            'artisan:config:clear',
            'artisan:migrate',
        ],

        'done' => [
            //
        ],
        
        'success' => [
            //
        ],
        
        'fail' => [
            //
        ],
    ],

    'options' => [
        'composer_action' => 'update',
        'application' => env('APP_NAME', 'Laravel'),
        'repository' => 'git@gitlab.com:user1/myappv.git',
        'writable_dirs' => [ "bootstrap/cache", "storage", "storage/app", "storage/framework", "storage/logs", "public/images" ],
        'writable_mode' => 'chmod',
        'writable_use_sudo' => 'true',
        'writable_chmod_recursive' => 'true',
        'writable_chmod_mode' => '0777',
        'shared_dirs' => [ "storage", "public/images"],
        'shared_files' => [".env"],
    ],

    'hosts' => [
        'xx.xxx.xxx.xxx' => [
            'deploy_path' => '/var/www/myapp',
            'user' => 'user1',
            'identityFile' => '~/.ssh/id_rsa',
            'stage' => 'production',
            'branch' => 'master',
        ],
    ],

    'localhost' => [
        //
    ],


    'include' => [
        'config/deploy_custom.php',
    ],

    'custom_deployer_file' => false,
];

**Comment by lorisleiva** [comment]
Hi there 👋 

Please refer to the documentation on how to create [custom tasks and recipes](https://github.com/lorisleiva/laravel-deployer/blob/master/docs/how-to-custom-recipes.md).

If I remember correctly, adding your recipes in the `config` folder will fail due to the fact that DeployerPHP does not use PSR-4. I suggest creating a new `recipes` folder for that.

**Comment by azril2018** [comment]
Thanks for the doc, bro. Done already.
