### ISSUE TITLE
Local .env variables used in Mix are deployed

### ISSUE THREAD

**Issue by rubendl** [lorisleiva/laravel-deployer#176]
Hi,

It is possible to inject environment variables into Laravel Mix ([docs](https://laravel.com/docs/7.x/mix#environment-variables)) and use them in the javascript assets that will be compiled with Webpack.

When using the local strategy, this means that those assets are compiled locally and instead of using the .env file on the target host, use the one on the local machine (in my case the local .env file has the development configuration, of which some MIX_ variables inadvertently end up in the production .js assets).

I believe the desired behavior would be to download the target host .env and use it to compile Mix assets locally before deploying.

**Comment by lorisleiva** [comment]
Hi there 👋 

I'm afraid MIX variables are not compatible with the local strategy.

If we had to support this, we'd need to download the `.env` file from the production server to the local environment and restore the previous `.env` file after the assets have been built which, for security purposes amongst other things, is not an option.

You'd need to use the `basic` strategy instead. I hope this helps.

**Comment by pmochine** [comment]
@lorisleiva It would be nice to have a warning banner for people that are reading about the local upload that it is not possible while using MIX

**Comment by simonbuehler** [comment]
hi,

is this also the same issue for the `upload` strategy?
when building in gitlab ci i'd like to have a way to add a .env ( or .en-example) file (that will be ignored on the deployment server anyways) as a source for the laravel mix variables needed on the server, is ther a way to do this?

**Comment by simonbuehler** [comment]
got it working see https://github.com/lorisleiva/laravel-deployer/issues/230#issuecomment-783430834
