### ISSUE TITLE
deploy issues (help needed)

### ISSUE THREAD

**Issue by Algeneralo** [lorisleiva/laravel-deployer#177]
Hi,
whenever I tried to deploy, it gives me this error for some reason

![image](https://user-images.githubusercontent.com/32073999/80439276-cf60da80-890e-11ea-8f8f-187f58b3be15.png)

I'm using Windows as OS, phpStorm as IDE to connect to ssh and other things 
could you please help with this?

**Comment by javalaw** [comment]
The Deployer provides a command `dep deploy:unlock`  to solve the problem caused by the deploy cancelled by "Ctrl+C", but laravel-deployer seems not wrap the command, sou you can ssh to your servser and cd to your project deploy path and rm the `.dep/deploy.lock` file manually.

**Comment by lorisleiva** [comment]
Hi there 👋 

I'm afraid this seems to be an issue regarding the SSH connection to your server.

I'm not familiar enough with Windows to help you debug this but I suggest posting this to StackOverflow or looking for results matching "getsockname failed not a socket".

Thank you for your understanding.

**Comment by zorca** [comment]
Option for Windows: `'multiplexing' => false,`
