### ISSUE TITLE
.env synchronization

### ISSUE THREAD

**Issue by ggolda** [lorisleiva/laravel-deployer#178]
Hi! Do you have plans to add a unified task that syncs `.env` file between multiple hosts? I think it will be useful because its a part of deployment routine and currently we have to write our own versions of that task.

Thanks!

**Comment by lorisleiva** [comment]
Hi there 👋 

Hmm... It would need to be generic enough for most deployment scenarios.

I'd love to see what such a task could look like. Feel free to write a PR and so we can discuss this at a more technical level. 🙂

**Comment by ggolda** [comment]
Sorry, I forgot to provide a result that I currently use 😄 
I decided to make a custom deployer "strategy" that will take a `.env.deploy-<stage>` (e.g. `.env.deploy-staging`) file from your local environment and upload it to hosts.

Here is how this script looks like:
```php
<?php

namespace Deployer;

use Exception;

set('env_file', function () {
    $stage = input()->getArgument('stage');
    if (!$stage) {
        writeln("<error>Stage is required to sync env files.</error>");
        throw new Exception("Stage is required to sync env files.");
    }

    $envFile = ".env.deploy-$stage";
    if (!file_exists($envFile)) {
        writeln("<error>Environment file not found: $envFile</error>");
        throw new Exception("Environment file not found: $envFile");
    }

    return (string) $envFile;
});

desc("Environment sync strategy");
task("strategy:env_sync", [
    'hooks:start',
    'env:upload',
    'artisan:config:cache',
    'fpm:reload',
    'artisan:horizon:terminate',
]);

desc("Upload environment file");
task("env:upload", function () {
    $envFile = get("env_file");
    if (!$envFile) {
        writeln("<error>env_file property not provided. Did you execute env:prepare task before?</error>");
        throw new Exception("env_file property not provided. Did you execute env:prepare task before?");
    }

    upload($envFile, "{{deploy_path}}/shared/.env");
});
```

As you can see it has some hardcoded steps, but for me its ok 😃 

To run an environment sync "strategy" you need to override a default strategy using a deployer flag:
`php artisan deploy <stage> -s env_sync`

**Comment by lorisleiva** [comment]
Awesome! Sorry for the late reply. Thank you for sharing this. I'm sure it will help other developers in this situation.

Since this is a logic that is dependent on a specific deployment flow, I don't think I should try and create a task that magically fits everyone need. Instead, your post will be most helpful for others to copy/paste/edit to their need.

Thanks again 🙂
