### ISSUE TITLE
Upload Strategy not uploading assets / js chunks

### ISSUE THREAD

**Issue by Sterioss** [lorisleiva/laravel-deployer#185]
Hi,
First of all, great package, great work.
I did set up my gitlab-ci to deploy on a restricted server using your upload strategy.

Issue is, I have to manually copy my storage assets + js compiled chunks.
It seems those files are not being uploaded. Maybe it has to do with the way gitlab artifacts work ?

I was wondering if setting a custom strategy would solve my issue.

Thank you !

**Comment by lorisleiva** [comment]
Hi there 👋 

The upload strategy should definitely be uploading your compiled assets. Are you sure they are being generated by the pipeline in the first place?

**Comment by Tim-Frensch** [comment]
I am seeing the same behavior. It's uploading the app.js and app.css just fine. The chunks are generated but skipped over.

**Comment by Sterioss** [comment]
If your pipeline uses fragments to cache your node, make sure it includes every js file a the base of the public folder.
This was my issue.
