### ISSUE TITLE
Local strategy doesn't work with multiple hosts

### ISSUE THREAD

**Issue by ggolda** [lorisleiva/laravel-deployer#187]
If I have multi-host environment (e.g. production have several servers) and I use local strategy to build them on 1 server and deploy code to multiple hosts, `local` part is executed for each host in a list, instead of only once. So if I have N servers I have to build frontend and other stuff N times.

Also this strategy doesn't work with deployer's `-p` flag and can not executed in parallel for multiple hosts. Error:

```
Output:                                                                                                                                                                          
  ================                                                                                                                                                                 
  Error Output:                                                                                                                                                                    
  ================                                                                                                                                                                 
  mkdir: cannot create directory ‘releases’: File exists 
```

**Comment by ggolda** [comment]
Is there a way to mix a frontend build tasks with composer install and this strategy? https://github.com/lorisleiva/laravel-deployer/blob/master/docs/strategy-upload.md

As I understand, upload strategy can be executed in parallel? And deployer supports task synching based on their documentation: https://deployer.org/docs/advanced/parallel-io.html

**Comment by lorisleiva** [comment]
Hi there 👋 

This package offers a few useful strategies to get you started but if you want something very custom and specific with multiple hosts in parallel, the best thing to do is to create your own tasks and list them in your own strategies.

That being said, I don't think DeployerPHP (the package that Laravel Deployer uses under the hood) supports tasks being executed before a multi-host parallel deployment. That is, I don't think you'll be able to create a local build first and _then_ start your parallel deployment (unless of course you do the build part in a shell script or something which defeats the purpose).
