### ISSUE TITLE
deploy:cleanup

### ISSUE THREAD

**Issue by mbaierl** [lorisleiva/laravel-deployer#189]
Hi,

how can I cleanup old releases? I found https://github.com/deployphp/deployer/blob/master/recipe/deploy/cleanup.php but have no idea how to call this recipe using artisan.

Thanks,
Michael

**Comment by asafov** [comment]
@mbaierl Use original source with laravel recipe, soon will be ready lumen app with REST API for deploy from external server or Homestead container.

**Comment by lorisleiva** [comment]
Hi there 👋 

Have you tried:

```
php artisan deploy:run deploy:cleanup
```

**Comment by mbaierl** [comment]
Hi, 
yes, gives me the following error:

> Command "deploy:cleanup" is not defined.

**Comment by lorisleiva** [comment]
Ah maybe the common deploy tasks are not namespaced. Have you tried this?

```sh
php artisan deploy:run cleanup
```

Btw, you can see all tasks available to you by running:

```sh
php artisan deploy:list
```

**Comment by mbaierl** [comment]
Hi @lorisleiva ,

that worked like a charm, thank you!

Michael
