### ISSUE TITLE
The command `artisan:migrate` is not executed on the production server

### ISSUE THREAD

**Issue by andrey-helldar** [lorisleiva/laravel-deployer#19]
My settings:
```php
'hooks' => [
    //...
    'ready'   => [
        //...
        'artisan:migrate',
    ],
```

When the command is started, the command is executed, but the migrations are not performed on the server.

If you manually run the `php artisan migrate` command on the server, the console raises the question: do I really want to start migration on `production` environment?
You either need to enter `yes`, or run the command with the key `--force`.

Tell me, what else have I not configured in the package?

**Comment by lorisleiva** [comment]
Hello, the `artisan:migrate` task runs with the `--force` flag by default:
https://github.com/lorisleiva/laravel-deployer/blob/261c55a4f5ca759f9f40ae4540687b77f7759d1a/src/task/artisan.php#L12

Could you provide me with the output of `php artisan deploy -vvv`?

**Comment by andrey-helldar** [comment]
```
вћ¤ Executing task artisan:migrate
[example.com] > if [ -s ~/www/example.com/releases/3/.env ]; then echo 'true'; fi
Warning: Your .env file is empty! Skipping...
```

**Comment by lorisleiva** [comment]
Yeah that makes sense. You're `.env` is empty so Laravel will not be able to connect to your database. Make sure to:
1. `cp .env.example .env` and `php artisan key:generate` in your server.
2. `vim .env` and insert your database credentials
3. Run `php artisan deploy` locally again.

If you need some help setting this up, I've already went through all this in a video on youtube: https://youtu.be/EaCd1ocep8A?t=3m15s

**Comment by andrey-helldar** [comment]
My site has been running on the server for a long time. Today I connected the deplorer to it.
If you start the migration from the server itself, then there is no problem.

**Comment by andrey-helldar** [comment]
I understood my mistake. When I first started, I used the config `'default' => 'basic'` instead `'default' => 'firstdeploy'`.

Now manually deleted all the files of the deplorer and launched the team with `firstdeploy` - everything worked perfectly.

Thanks!

**Comment by lorisleiva** [comment]
In that case it's because your `.env` file is in your root path and not in the `shared` folder.

You might want to take a look at the `firstdeploy` strategy which was created for that exact purpose. This is how I personally migrated my projects to use Laravel Deployer.

https://github.com/lorisleiva/laravel-deployer/blob/261c55a4f5ca759f9f40ae4540687b77f7759d1a/docs/strategy-first-deploy.md

**Comment by andrey-helldar** [comment]
Yes, I understood my mistake. Thank you!

I watched the video you gave in the previous comments and adjusted the way it should. Now everything works. Once again many thanks!
