### ISSUE TITLE
Run bash command after deploy

### ISSUE THREAD

**Issue by francesco-taioli** [lorisleiva/laravel-deployer#190]
Hi, it's possible to run a specif sh script after deploy?
I have a script that update the folder permission and other things.
I've see that exist a `php artisan deploy:run` but it seems that it accept a task, not a command.

The result in my mind is something like this:  `php artisan deploy:xx "cd /var/www && ./myscript.sh"`

It's possible?
Thanks

**Comment by simonbuehler** [comment]
@francesco-taioli 
hi, i have the same issue, did you manage to make this work?

**Comment by simonbuehler** [comment]
ok found it in https://github.com/lorisleiva/laravel-deployer/issues/65#issuecomment-437341236
