### ISSUE TITLE
CD command throws error with every request under certain conditions

### ISSUE THREAD

**Issue by andrewmarconi** [lorisleiva/laravel-deployer#192]
In ```src/LaravelDeployer/ConfigFileBuilder.php```, line 53:

```
$this->set('options.repository', exec("cd $basePath && git config --get remote.origin.url") ?? '');
```

Could be written more safely as:

```
$this->set('options.repository', exec('cd "$basePath" && git config --get remote.origin.url') ?? '');
```

If any part of the project's source code path contains a space, this line of code treats the path as two separate arguments.  The side effect is that because ConfigFileBuilder is instantiated with every request, it throws an error on each request. Wrapping the variable in quotes prevents this behavior.

I realize that in production, the change of having a space in the path is nearly nil, but in development it is entirely possible (esp on macOS).

**Comment by lorisleiva** [comment]
Good catch! PR welcome 😊

**Comment by lucadello91** [comment]
This cause a bug on some system
See #206
