### ISSUE TITLE
Permission are too high. A lot of folders have 777

### ISSUE THREAD

**Issue by AEM5299** [lorisleiva/laravel-deployer#193]
Hello,

I tried to deploy with this package using the upload strategy, didn't make much changes except enable the vendor directory to be uploaded. The deployment process finished successfully, but there are a lot of folders that have 777 permissions. Not sure if this is the correct default behaviour or did I miss configure something. Either way I would like to change that. Went through the docs & exisiting issues but didn't find anything relevant. See below image for the directory permissions.
![Screen Shot 2020-07-05 at 6 11 05 pm](https://user-images.githubusercontent.com/38721478/86528417-e6154600-beea-11ea-85d7-e0aa18410551.png)

**Comment by AEM5299** [comment]
Ended up being a problem in the pipeline.

**Comment by goors** [comment]
i have same problem? can you tell me what you problem was?

**Comment by AEM5299** [comment]
@goors I am using bitbucket pipeline and for me the solution was to simply iterate over the directory and set the desired permissions.
```
- find . -type f -not -path "./vendor/*" -exec chmod 664 {} \;
- find . -type d -not -path "./vendor/*" -exec chmod 775 {} \;
```
