### ISSUE TITLE
Wrong cached database config after laravel 7 upgrade.

### ISSUE THREAD

**Issue by walidbagh** [lorisleiva/laravel-deployer#198]
Hey, i just upgraded to laravel 7, and my cd pipe keep failing with the following:

![Capture1](https://user-images.githubusercontent.com/7133090/89233058-197dea00-d5e9-11ea-9b7f-8168bb7de959.PNG)

I checked the created (but failing) release folder [Release 19] and i found 2 things:
1)- The correct .env file from shared folder is symlinked.
```
DB_CONNECTION=mysql
DB_HOST=localhost
DB_PORT=3306
DB_DATABASE=[REDACTED]
DB_USERNAME=[REDACTED]
DB_PASSWORD=[REDACTED]
```
2)- The cached config file under /bootstrap/cache/config.php, has the wrong values for DB_USERNAME & DB_PASSWORD, despite having the correct DB_HOST from .env 

![Capture](https://user-images.githubusercontent.com/7133090/89233520-07e91200-d5ea-11ea-935a-580da2b402d3.PNG)

Even trying to deploy from my local machine, yields the same error.
When running config:cache inside the [Release 19] folder then migrating, the migration works.
@lorisleiva any idea about this ?

**Comment by lorisleiva** [comment]
Hi there 👋 

That's strange. How do you update your `.env` file at the moment? SSH into the host and update it there?

If you run the deploy command with `-vvv`, you might get more information on what is being executed during the deployment flow.

**Comment by walidbagh** [comment]
Thank you for your reply,

1- This isn't the first time that i'm deploying, everything was working correctly before updating to laravel 7, i'm using your package to deploy to dev and production website, and followed your videos on how to setup the vps ( which are great videos <3 ).

2- YES, i double checked the `.env` in the shared folder, and as i mentioned in above, it gets symlinked correctly to the new release folder, and has the correct values for database.

```
DB_CONNECTION=mysql
DB_HOST=localhost
DB_PORT=3306
DB_DATABASE=kimo_dev
DB_USERNAME=user
DB_PASSWORD=P@ssword
```

3- As you may note from the error image above, the `DB_DATABASE` value get correctly cached [ table_schema = kimo_dev ] , but `DB_USERNAME` and `DB_PASSWORD` get cached to 'root' and ''.
And if i do a `php artisan config:cache` inside the release folder, then the migrations work and correct `.env` values get cached.

4- Here is my database config file:
```
...
    'default' => env('DB_CONNECTION', 'mysql'),

    'connections' => [

        'mysql' => [
            'driver' => 'mysql',
            'url' => env('DATABASE_URL'),
            'host' => env('DB_HOST', '127.0.0.1'),
            'port' => env('DB_PORT', '3306'),
            'database' => env('DB_DATABASE', 'forge'),
            'username' => env('DB_USERNAME', 'forge'),
            'password' => env('DB_PASSWORD', ''),
            'unix_socket' => env('DB_SOCKET', ''),
            'charset' => 'utf8mb4',
            'collation' => 'utf8mb4_0900_ai_ci',
            'prefix' => '',
            'prefix_indexes' => true,
            'strict' => true,
            'engine' => null,
            'options' => extension_loaded('pdo_mysql') ? array_filter([
                PDO::MYSQL_ATTR_SSL_CA => env('MYSQL_ATTR_SSL_CA'),
            ]) : [],
        ],
...
```
5- Here is the output with `-vvv`: 
[output.sh](https://gist.github.com/walidbagh/9de447d724ade1e774a07ef62552f299)

**Big Question**: where are the values 'root' and '', coming from ?

**Comment by lorisleiva** [comment]
Hey, did you find out what was causing this issue in the end? I had a look at your points above and your output file but couldn't make sense of what was happening. Was this perhaps an OPcache issue?

**Comment by walidbagh** [comment]
By the end, i found out that laravel was loading the wrong .env files.

In my case, i have 2 files `.env.dev` and `.env.prod` , that i use as template, laravel never loaded values from them in the last 4 years!

But now, laravel 7 just did :(

So i renamed those files to a format that wont confuse laravel.

The weird thing is that nothing changed in the env loading logic between x6 and x7 : [link](https://github.com/laravel/framework/blob/75792f4c6945749046d4ec1ce560b04640d36b99/src/Illuminate/Foundation/Bootstrap/LoadEnvironmentVariables.php#L58)

**Comment by lorisleiva** [comment]
Oh okay. Yeah that’s pretty strange but I’m glad you managed to find a solution in the end 🙂
