### ISSUE TITLE
How to deploy node_modules to server

### ISSUE THREAD

**Issue by ismatBabirli** [lorisleiva/laravel-deployer#200]
Hi. I want to deploy node_modules of my laravel project but I can't find any resource about this. Can anyone help me?

**Comment by mattkibbler** [comment]
Hi @ismatBabirli. The `node_modules` directory should be created if you use the `npm:install` task in your deployment process. I think this should be added under the `build` section of the `hooks` array in your `deploy.php` config, like so:

```
return  [
    'hooks' => [
        'build' => [
            'npm:install',
        ]
    ]
];
```
