### ISSUE TITLE
Double quote on cd command not working with ~

### ISSUE THREAD

**Issue by lucadello91** [lorisleiva/laravel-deployer#206]
Hello
I updated the package and the deployment stopped working due to this error:

`The command "cd "~/httpdocs/releases/71" && /usr/local/bin/composer install --verbose --prefer-dist --no-progress --no-interaction --no-dev --optimize-autoloader --no-suggest" failed.`

This happens when using ~ for paths.

Is there a workaround other than using an older version of this package or insert a full path?
Thanks

**Comment by lorisleiva** [comment]
Ergh, thank you for reporting this! 🙏 

I wonder if we could try single-quotes instead since I think it won't be parsing as much as double-quotes.

@hypnodev What do you think? Would that still work in your case?

I'm happy to revert PR #199 if we can't fix this in another way.

**Comment by andrecolza** [comment]
I'm having the same issue, tried replacing double-quotes by single-quotes in package, but it still not work.
The only workaround seems to remove quotes completely, by this way it works.

**Comment by hypnodev** [comment]
@lorisleiva we can fix it with adding a check before adding quotes, so if the path contains "whitespace" we need to add quotes instead if the path doesn't contains path we not need to add the quotes. 

If you agree with me I can do this hot fix immediately

**Comment by andrey-helldar** [comment]
![image](https://user-images.githubusercontent.com/10347617/93350724-9edbf780-f841-11ea-9d47-fd1d2503ccb8.png)

The `cd ~/www` command treats the tilde character as a relative path, while its indication in quotes is interpreted by the unix system as a folder name.

`cd ~/www` - works
`cd "~/www"` - doesn't works
`cd '~/www'` - doesn't works
`cd /home/me/www` - works
`cd "/home/me/www"` - works
`cd '/home/me/www'` - works

**Comment by lorisleiva** [comment]
I'm inclined to think that we should revert PR #199 because it makes the `deploy_path` option less flexible.

If your `deploy_path` contains whitespaces then it is possible to wrap it in double-quotes inside the config file directly like so:

```php
'deploy_path' => '"/home/my/path with/spaces"'
```

**Comment by andrey-helldar** [comment]
> I'm inclined to think that we should revert PR #199 because it makes the `deploy_path` option less flexible.
> 
> If your `deploy_path` contains whitespaces then it is possible to wrap it in double-quotes inside the config file directly like so:
> 
> ```
> 'deploy_path' => '"/home/my/path with/spaces"'
> ```

In my opinion, using spaces in paths is very bad.

**Comment by lorisleiva** [comment]
Reverted and released as `v0.3.4`. 🚀 

Wrapping the `deploy_path` with quotes will actually fail for tasks like `cd {{deploy_path}}/current` so we might need to revisit and find a better way to support paths with spaces but we need to make sure it does not cause breaking changes.

**Comment by Jamesking56** [comment]
I seem to recall being able to add a backslash before spaces in the path to escape them? Such as:

`/home/user/my\ cool\ path/`

This way it doesn't need quoting? Worth a test?
