### ISSUE TITLE
How do I use this on Shared Hosting

### ISSUE THREAD

**Issue by Stancobridge** [lorisleiva/laravel-deployer#212]
Hello am having an issue using this when I run `php artisan deploy`
✈︎ Deploying master on lwbinternational.org with basic strategy
➤ Executing task deploy:prepare
✔ Executing task deploy:failed
➤ Executing task deploy:unlock

In Client.php line 103:
                                                                                    
  The command "rm -f /home/lwbidkzz/lwbinternational.org/.dep/deploy.lock" failed.  
                                                                                    
  Exit Code: -1 (Unknown error)                                                     
                                                                                    
  Host Name: lwbinternational.org                                                   
                                                                                    
  ================                                                                  
  ssh: connect to host lwbinternational.org port 22: Connection refused

**Comment by lorisleiva** [comment]
You cannot because you need SSH access to your server.
