### ISSUE TITLE
`local:cleanup` removes the uploaded site

### ISSUE THREAD

**Issue by andrey-helldar** [lorisleiva/laravel-deployer#213]
> ➤ Executing task cleanup
> [127.0.0.1] > cd /home/helldar/www && if [ -e release ]; then  rm release; fi
> [127.0.0.1] > cd /home/helldar/www && if [ -h release ]; then  rm release; fi
> • done on [127.0.0.1]
> ✔ Ok [287ms]
> ➤ Executing task local:cleanup
> [localhost] > rm -rf /home/helldar/www
> ✔ Ok [797ms]
> • done on [127.0.0.1]
> • done on [127.0.0.1]
> 🚀  Successfully deployed in 51.53s
> Application successfully deployed

Result:

![image](https://user-images.githubusercontent.com/10347617/96465152-4ed1c580-1231-11eb-9a7e-0afb31b1d49e.png)

Config:

```php
<?php

return [

    'default' => 'local',

    'strategies' => [],

    'hooks' => [
        'start' => [],

        'build' => [],

        'ready' => [],

        'done' => [],

        'success' => [],

        'fail' => [],

        'rollback' => [],
    ],

    'options' => [
        'application' => env('APP_NAME', 'Laravel'),
        'repository'  => 'git@<my_gitlab_address>.git',

        'php_fpm_service' => 'php7.4-fpm',

        'http_user' => 'helldar',

        'local_deploy_path' => '/home/helldar/www',

        'local_upload_options' => [
            'options' => [
                '--exclude=.git',
                '--exclude=vendor',
            ],
        ],
    ],

    'hosts' => [
        '127.0.0.1' => [
            'deploy_path' => '/home/helldar/www',
            'user'        => 'helldar',
        ],
    ],

    'localhost' => [],

    'include' => [],

    'custom_deployer_file' => false,

];
```

**Comment by lorisleiva** [comment]
Hi there, yes this is by design since, by default, the locally built application is only temporary created within your vendor folder. Feel free to create a new custom strategy that copies all of the tasks inside that strategy minus the `local:cleanup`. 🙂
