### ISSUE TITLE
[composer 3] deprecated option "--no-suggest"

### ISSUE THREAD

**Issue by andrey-helldar** [lorisleiva/laravel-deployer#214]
> You are using the deprecated option "--no-suggest". It has no effect and will break in Composer 3.

![image](https://user-images.githubusercontent.com/10347617/96557800-72dde700-12c3-11eb-9dfc-5361967e3d8a.png)

**Comment by lorisleiva** [comment]
Good shout! PR welcome 🙂

**Comment by andrey-helldar** [comment]
I sent the PR to the parent project: https://github.com/deployphp/deployer/pull/2212

**Comment by lorisleiva** [comment]
Thank you for that! The only thing is IIRC `master` will only be part of Deployer 7.x which is still in beta.

Currently, Laravel Deployer uses Deployer 6.x (the latest stable).

We can either wait for 7.x to become available or push another PR to the `6.x` branch. It's up to you. 🙂

**Comment by andrey-helldar** [comment]
Okay https://github.com/deployphp/deployer/pull/2213 ☺
