### ISSUE TITLE
how to set composer.phar version

### ISSUE THREAD

**Issue by thoriqabdul** [lorisleiva/laravel-deployer#217]
I'm having problems when i deploying my project

➤ Executing task deploy:vendors
➤ Executing task deploy:failed
✔ Ok
➤ Executing task deploy:unlock
✔ Ok
Error Output:
================
In Client.php line 103:
                                                                               
  The command "cd /var/www/laravel/releases/95 && /usr/bin/php /var/www/larav  
  el/releases/95/composer.phar install --verbose --prefer-dist --no-progress   
  --no-interaction --no-dev --optimize-autoloader --no-suggest" failed.        
                                                                               
  Exit Code: 1 (General error)                                                 
                                                                               
  Host Name: steging.jagomaterial.id                                           
                                                                               
  ================                                                             
  You are using the deprecated option "--no-suggest". It has no effect and wi  
  ll break in Composer 3.                                                      
  Installing dependencies from lock file                                       
  Verifying lock file contents can be installed on current platform.           
  Dependency resolution completed in 0.000 seconds                             
  Package operations: 79 installs, 0 updates, 0 removals                       
  Installs: symfony/polyfill-ctype:v1.13.1, phpoption/phpoption:1.7.2, vlucas  
  /phpdotenv:v3.6.0, symfony/css-selector:v5.0.2, tijsverkoyen/css-to-inline-  
  styles:2.2.2, symfony/polyfill-php72:v1.13.1, symfony/polyfill-mbstring:v1.  
  13.1, symfony/var-dumper:v4.4.2, symfony/routing:v4.4.2, symfony/process:v4  
  .4.2, symfony/polyfill-php73:v1.13.1, symfony/polyfill-intl-idn:v1.13.1, sy  
  mfony/mime:v5.0.2, symfony/http-foundation:v4.4.2, symfony/event-dispatcher  
  -contracts:v1.1.7, symfony/event-dispatcher:v4.4.2, psr/log:1.1.2, symfony/  
  debug:v4.4.2, symfony/error-handler:v4.4.2, symfony/http-kernel:v4.4.2, sym  
  fony/finder:v4.4.2, psr/container:1.0.0, symfony/service-contracts:v2.0.1,   
  symfony/console:v4.4.2, symfony/polyfill-iconv:v1.13.1, doctrine/lexer:1.2.  
  0, egulias/email-validator:2.1.14, swiftmailer/swiftmailer:v6.2.3, paragoni  
  e/random_compat:v9.99.99, ramsey/uuid:3.9.2, psr/simple-cache:1.0.1, opis/c  

i got this on my log stacktrace : 

[2020-10-26 14:51:00] local.ERROR: Undefined index: name {"exception":"[object] (ErrorException(code: 0): Undefined index: name at /var/www/laravel/releases/95/vendor/laravel/framework/src/Illuminate/Foundation/PackageManifest.php:131)
[stacktrace]

https://stackoverflow.com/questions/61177995/laravel-packagemanifest-php-undefined-index-name

when I run composer.phar -v on the server, I get my composer version 2.0

Do You have any advice?

Thanks

**Comment by timkley** [comment]
See #214

This has been fixed in `main` but not released yet. You can set your `composer`_options manually in your `deployer.php` file.

**Comment by lorisleiva** [comment]
Hi there 👋 

I'm closing this issue since Laravel Deployer is no longer the package it used to be and I recommend using Deployer directly for your Laravel applications from now on.

I've written a series of detailed tutorials to get started with Deployer called "[Deploy your Laravel app from scratch](https://lorisleiva.com/deploy-your-laravel-app-from-scratch)".

Thank you for all the support I've had whilst maintaining this package. I'm now also a maintainer of the Deployer library so feel free to open Laravel-related discussions on the repo and I'll help you there.

Happy deploying! 🌺
