### ISSUE TITLE
Install only in dev?

### ISSUE THREAD

**Issue by underdpt** [lorisleiva/laravel-deployer#220]
Hi,

Per documentation, laravel-deployer is installed on `required`, so it's being "deployed" to production. Shouldn't it be installed only on development environment (`required-dev`)? Does the package need to be installed on the deployment server to work as intended?

**Comment by lorisleiva** [comment]
Hi, both are valid options. I often using it to deploy from Forge with zero downtime so in that case I’d need to have it in the production dependencies.

If you only need to deploy from local machines then indeed, adding the `--dev` option is a good idea.
