### ISSUE TITLE
PHP 8.0 Compatible

### ISSUE THREAD

**Issue by ricklambrechts** [lorisleiva/laravel-deployer#222]
Current version of deployphp/deployer(6.8.0) depends on "php": "^7.2".

**Comment by sefaYavuz** [comment]
Getting the same error for php 8.

```
    - deployer/deployer[v6.1.0, ..., v6.7.1] require php ~7.0 -> your php version (8.0.0) does not satisfy that requirement.
    - deployer/deployer[v6.7.2, ..., v6.8.0] require php ^7.2 -> your php version (8.0.0) does not satisfy that requirement.

**Comment by dbrowny** [comment]
Any update on this?

**Comment by lorisleiva** [comment]
Hi there 👋 

Thanks for raising this. I don't have time to handle this at the moment but a PR would be most welcome. 🙇‍♂️

**Comment by judge2020** [comment]
Installing with `--ignore-platform-req php` seems to work if anyone is in the mood to test the code on PHP 8.

**Comment by repat** [comment]
It also depends on `deployer/recipe` (which is abadoned btw) and the requirement of that is `php: ~7.0`.

Any plans to move away from the recipe package, @lorisleiva? :)

**Comment by andrey-helldar** [comment]
![image](https://user-images.githubusercontent.com/10347617/104513345-908bc580-5600-11eb-8a5f-e39c03520d0f.png)

https://packagist.org/packages/deployer/deployer

**Comment by lorisleiva** [comment]
That’s only for 7.x though which is still in beta. Laravel Deployer is using the latest stable which is 6.x.

That’s out of the scope of this issue though. There’s another issue mentioning this IIRC.

**Comment by andrey-helldar** [comment]
That is why I have attached a screenshot with information about the beta versions of the deployer. So that people know, everything is about to be ready 😊

**Comment by nabilelmahiri** [comment]
Hello, thank you for the great work first, any updates on the new version fully compatible with php 8 ?, the solution mentioned above didn't work for me !

**Comment by blackjak231** [comment]
@lorisleiva Would it be possible to have a beta branch of Laravel Deployer which uses the latest beta of Deployer 7.x ?

**Comment by calebanthony** [comment]
I second this. The official Deployer repo just released another V7 beta and it looks like there are still open issues for V7 with no timeline or roadmap for an official release.

**Comment by lorisleiva** [comment]
I agree. 🙂

I’ll take care of it when I’ve got some free time but feel free to PR something in the meantime.

**Comment by sergyu91ma** [comment]
so you took care :D, we will use deployer directly :)

**Comment by lorisleiva** [comment]
Hi there 👋 

I'm closing this issue since Laravel Deployer is no longer the package it used to be and I recommend using Deployer directly for your Laravel applications from now on.

I've written a series of detailed tutorials to get started with Deployer called "[Deploy your Laravel app from scratch](https://lorisleiva.com/deploy-your-laravel-app-from-scratch)".

Thank you for all the support I've had whilst maintaining this package. I'm now also a maintainer of the Deployer library so feel free to open Laravel-related discussions on the repo and I'll help you there.

Happy deploying! 🌺

**Comment by smknstd** [comment]
Do you have any information about php8 support with https://github.com/deployphp/deployer ? Thanks

**Comment by Jamesking56** [comment]
@smknstd PHP 8 support works if you use the beta versions of Deployer

**Comment by smknstd** [comment]
just found out about this page https://github.com/deployphp/deployer/discussions/2351

**Comment by applyACS** [comment]
Still no php8 support for this and for [deployer](https://github.com/deployphp/deployer)
deployer has a 7.0 release with php8 support but this package still requires ^6.1 version
