### ISSUE TITLE
Thanks

### ISSUE THREAD

**Issue by iBotPeaches** [lorisleiva/laravel-deployer#238]
Thanks for the package. I imagine the parent package has caught up and made this easier to support natively and lessen the burden on you to maintain something.

Used it in many many projects and upgrading them to deployer7/php8 slowly.

**Comment by lorisleiva** [comment]
Thanks for the kind words! I'm currently writing a big series that deploys a Laravel app from scratch using Deployer which I hope will help users the same way this package did before. 🙂
