### ISSUE TITLE
upload .env file based on destination - question: how to achieve in YAML?

### ISSUE THREAD

**Issue by wivaku** [lorisleiva/laravel-deployer#239]
**Suggestion**: instead of manually copying the `.env` file to the server, this could be done as part of the deploy process.
**Question**: how to call API commands as part of the `deploy.yaml` file?

I maintain my `.env` files on my dev system and upload them to the destinations as part of the deploy process.
This works fine using `deploy.php`, but I'm not sure how to run API commands from `deploy.yaml`.

In deploy.php I have:
```
host('prod')
...
  ->set('env_file', '.env.production')

task('deploy', [
    'deploy:prepare',
    'deploy:vendors',
    'artisan:storage:link',
    'laravel:uploadEnv',
...

task('laravel:uploadEnv', function () {
    if (testLocally('[ -f {{env_file}} ]')) {
        upload('{{env_file}}', '{{deploy_path}}/shared/.env');
    } else {
        writeln('env file does not exist: {{env_file}}');
    }
})->desc('upload .env to shared folder of deploy path');
```

Is it possible to do something similar in `deploy.yaml`?

**Note**: make sure to add to `.gitignore`:  
```
.env*
!.env.example
```

**Comment by lorisleiva** [comment]
Hi there 👋 

Not really, it's best to create a custom recipe that you store somewhere in your repo — for example `deploy/upload-env.php` and then you import it in your `deploy.yaml` file allowing you to add the custom task to your `deploy` task.

I'm going to talk about all this in a follow up article on my blog. 🙂

**Comment by wivaku** [comment]
That makes sense as a workaround, thanks!
