### ISSUE TITLE
Load Balance

### ISSUE THREAD

**Issue by emotality** [lorisleiva/laravel-deployer#24]
Hi, I would like to use this, but have a question.

Is this load balance ready?

I have 4 servers that are load balanced and needs to be in sync for deploy. Usually 1 machine is slower than the rest, even if I start the deploy earlier and this is a gamble.

Please advise, thanks! 😊

**Comment by lorisleiva** [comment]
Hello 👋 

You can certainly use this with load balanced servers but, as you mentioned, the synchronisation won't be perfect. 

By default Deployer (the underlying technology of Laravel Deployer) runs deployment on every host one by one but you can provide a `--parallel` option which makes them deploy at the same time. [See Deployer's documentation](https://deployer.org/docs/tasks#parallel-task-execution). 

You can also provide this parallel option to Laravel Deployer like this: `php artisan deploy --parallel`.

I am aware this is not the perfect sync that you might be looking for but I hope this helps.

**Comment by emotality** [comment]
Awesome, that helps a lot thanks! Sorry I missed that 🙈 

My next question would've been, how would one host be aware of the other, but [this](https://deployer.org/docs/hosts#multiple-hosts) answers it! 

Thanks man, will go through complete docs 😉
