### ISSUE TITLE
 Could not find package deployer/deployer in a version matching 7.0

### ISSUE THREAD

**Issue by haideritx** [lorisleiva/laravel-deployer#242]
Using Laravel Version 8, and php version 7.4
I also tried with updated composer version 2.x

Trying to install deployer through composer, but getting error.

```
 Could not find package deployer/deployer in a version matching 7.0
```

![image](https://user-images.githubusercontent.com/26646476/117903211-8e085680-b2e8-11eb-8df1-aba047d38626.png)

**Comment by torshid** [comment]
You can specify the current latest version like that:
```
composer require deployer/deployer:v7.0.0-beta.23
```
