### ISSUE TITLE
Include Liquidpromt

### ISSUE THREAD

**Issue by simonbuehler** [lorisleiva/laravel-deployer#246]
Hi,

no bug, just to say a big *thank you* 🥇  for your series writeup, its a awesome read and walk through even when coming from the "old" deployer.

one little nerdy thing: using [liquidpromt](https://github.com/nojhan/liquidprompt) makes the bash even nicer to use especially with the  [Powerline Theme](https://liquidprompt.readthedocs.io/en/stable/theme/included/powerline.html#powerline-theme)

thanks for your work!

**Comment by lorisleiva** [comment]
Aw thank you! And thanks for sharing that terminal tip! 😍
