### ISSUE TITLE
After each deployment, all users are logged out 

### ISSUE THREAD

**Issue by forPelevin** [lorisleiva/laravel-deployer#25]
Hi Loris,

I faced with the problem: everytime when I deploy the app then everyone is logged out forcibly. 
Do you have any idea why it could be in that way?

Thanks

**Comment by lorisleiva** [comment]
Hello, This is a weird one. Could you tell me which tasks are called within your deployment process? It must have something to do with cache flushing. Are you authenticating your users using the traditional Laravel way?

**Comment by lorisleiva** [comment]
Oh well this makes sense then. You should probably avoid clearing the entire cache and clear specific caches instead (like the config cache, etc.). I hope this helps.

**Comment by forPelevin** [comment]
Hmm, I see that works. 
Thanks a lot! :)
