### ISSUE TITLE
Lumen Support

### ISSUE THREAD

**Issue by semsphy** [lorisleiva/laravel-deployer#3]
How can I integrate in LUMEN?

Thanks,

**Comment by lorisleiva** [comment]
Hi there, I am currently working on adding support for Lumen. I'll let you know as soon as it's ready and documented. Hopefully, when done, it should be as easy to set up as adding `set('lumen', true);` to your `deploy.php`.

**Comment by lorisleiva** [comment]
Lumen deployments are now supported and documented [here](https://github.com/lorisleiva/laravel-deployer/blob/master/docs/how-to-lumen.md).

**Comment by semsphy** [comment]
Greeting from Cambodia, thank you very much.
