### ISSUE TITLE
No application encryption key has been specified.

### ISSUE THREAD

**Issue by Cookizza** [lorisleiva/laravel-deployer#33]
Hi there,

I've got the latest version of deployer and following the setup has been no issue.

I've setup a .env in the shared folder however after deploying i get the error

`No application encryption key has been specified.`

The migrations ran, so it's reading the env file - and i can see a key set there..

Any pointers?

**Comment by lorisleiva** [comment]
Hello 👋 

I see you've fixed your issue. Could you please let me know what went wrong?

**Comment by vrajroham** [comment]
@Cookizza @lorisleiva I'm facing the same issue. Can you please help how you resolved it? I tried copying .env directly into current release folder too, but no luck.

**Comment by vrajroham** [comment]
@Cookizza Thank you so much! This works :) I tried multiple ways but didn't work earlier.

**Comment by Cookizza** [comment]
No problem!
