### ISSUE TITLE
Running horizon:terminate after symlinking

### ISSUE THREAD

**Issue by fgilio** [lorisleiva/laravel-deployer#34]
Hi @lorisleiva !
I'm having some weird issues where I've to manually log into the server and run `artisan horizon:terminate` for my changes to replicate.
So while I was thinking about this issue I thought that maybe php-fpm should be reloaded before `horizon:terminate`, but in writing this issue I realized that Horizon is not using fpm.
But, maybe Supervisord is restarting Horizon before the symlink takes place and the new release is set as current. Wouldn't it make more sense to trigger the `artisan:horizon:terminate` task in the `done` hook?

---

For example when using Forge, Supervisord has no idea of what's the latests release. This is the daemon I have:
User `forge` runs command `php artisan horizon` at path `/home/forge/{the-project-dir}/current/`

**Comment by lorisleiva** [comment]
Hi there 👋 

This is odd. I use Forge's deamons the same way you do and I have not witnessed this error before.

Have you tried to deploy using the task `artisan:horizon:terminate` within the `done` hook? Does that fix the problem?

Also, did you check the [troubleshooting section](https://github.com/lorisleiva/laravel-deployer/blob/493f5e6ab721c8e442244bc59cd1a4b5a449ad47/docs/troubleshooting.md#my-changes-dont-show-up-after-a-deployment) about problems with symlinks and php fpm?

**Comment by fgilio** [comment]
Hello!
Maybe this is related to this https://github.com/laravel/horizon/issues/213

Anyway, I'm going to try using the task `artisan:horizon:terminate` within the `done` hook and let you know if that fixes it.

**Comment by fgilio** [comment]
Sorry for the delay.
This is the hook's code:
```bash
cd {{release}}
php artisan horizon:terminate
```
But, keep in mind that all this is bun **after** activating the new release.

Still had no time to try with using the task `artisan:horizon:terminate` within the done hook, but I'll let you know as soon as that happens.

**Comment by lorisleiva** [comment]
Sure no problem take your time. Keep me posted 🙂

**Comment by jlsjonas** [comment]
Just noticed a similar but likely related behaviour... my config was not updated; at all...
I switched databases from a temp. test to the actual one. noticed the tables weren't there (migrate didn't happen; or happened on the wrong server)
went into current (as deployment was successful) and did a manual migrate; noticing it was still trying to do it to the old DB.

So it seems that the cache files aren't being cleared correctly before symlinking; which also means that we can't do proper zero-downtime deploys as we have to clear the cache in done (or manually) to actually have them propagate...

Any ideas why this is happening?

**Comment by fgilio** [comment]
Mmm I can try to replicate that. I'll create a new empty db in a staging server, update .env and just trigger a redeploy of the lastest commit.
Can you share your deploy.php? In case there's a config difference

**Comment by fgilio** [comment]
Well, took a long time to actually get to test this. I got everything working as expected *with fpm:reload and artisan:horizon:terminate running in the done block*:
```php
        'done' => [
            'fpm:reload',
            'artisan:down_if_migrate',
            'artisan:migrate',
            'artisan:up',
            'artisan:horizon:terminate',
        ],
```
Also couldn't replicate @jlsjonas problem :\
