### ISSUE TITLE
Check for migrations and enter maintenance mode accordingly

### ISSUE THREAD

**Issue by fgilio** [lorisleiva/laravel-deployer#35]
Hello!
While I love zero downtime deployments, sometimes it's either just not possible or just to hard to be worth it. Most of the times it's because database migrations.

I'm using Laravel Envoyer for some projects and I would like to stop using it, as I'm moving everything I can to GitLab and it's pipelines (thanks for the posts by the way, got me started on this path).
One nice thing I've setted up with Envoyer and by using [laravel-migrate-check](https://github.com/erjanmx/laravel-migrate-check) is that the deploy only triggers `artisan down` if there're migrations to run (I think `artisan up` runs every time).

It's super simple and I'm sure I could build it myself using custom tasks (already have one for yarn), but at the same time I thought that maybe this could be bundled in Laravel Deployer.

I'm curious to know what you think. Thanks for Laravel Deployer, it's really great 👏 

---

This is the command I run to enter maintenance mode:
```bash
if ! php artisan migrate:check ; then php artisan down; fi
```

**Comment by lorisleiva** [comment]
Hello again 👋 

Yes it is a good idea and I would like to make it easier for you to use this approach.

First of all, there are two existing tasks to up and down your application, `artisan:up` and `artisan:down` respectively.

The missing task that I could implement would be something like `artisan:down_if_migrate`. Then all you would need to do is wrap your `artisan:migrate` task between `artisan:down_if_migrate` and `artisan:up`.

Would such implementation be useful to you?

---

> Most of the times it's because database migrations.

Are there any other frustrations that you have with Laravel Deployer that we could improve on?

**Comment by fgilio** [comment]
Hey! I'm glad you found this suggestion useful. And, yes, that sounds pretty nice and straightforward.

---

> Are there any other frustrations that you have with Laravel Deployer that we could improve on?

None yet 🎉 , but I'll make sure to keep the suggestions coming while moving to the new delivery workflow.

**Comment by lorisleiva** [comment]
Hey, by re-reading your message, I've now realised that `migrate:check` is not part of Laravel by default. It's a shame it is a pretty decent feature.

As a result, if I had this task to the core of Laravel Deployer, I am worried that users might try to use it without the required dependency. If it was a very popular package I would have probably added a warning that says "Please download this package to use this task" but I feel like it is a bit of an overkill in that case.

Nevertheless I have prepared the task so that you (and future users reading this threat) can still benefit from this feature.

```php
desc('Enable maintenance mode only if some migrations need to be run');
task('artisan:down_if_migrate', function() {

    // If migrate:check is 0 then no need to enable maintenant mode.
    if (test("! {{bin/php}} {{release_path}}/artisan migrate:check")) {
        return;
    }
    
    // Otherwise enable maintenance mode on the `current` folder.
    $output = run("{{bin/php}} {{deploy_path}}/current/artisan down");
    writeln("<info>$output</info>");
});
```

Note that in order to create your own tasks, you'd have to [create and include your own recipe](https://github.com/lorisleiva/laravel-deployer/blob/3d168965b385a096fec7fffa3fb9e3fb47adaba2/docs/how-to-custom-recipes.md#how-to-create-your-own-tasks-and-recipes) first.

Please don't hesitate to share your code if you build on this. I hope this helps. 🤞

**Comment by fgilio** [comment]
Thank you very much! I'm probably gonna try it today.

**Comment by fgilio** [comment]
It's been a while and this has been working as it's supposed to 👍

**Comment by lorisleiva** [comment]
Oh perfect, thanks for letting me know! 🙂

**Comment by fgilio** [comment]
We're now starting to use this workflow for production deployments and yesterday I realized that this task was not working as expected, and it entered maintenance mode every time it run. I tried to fix it but couldn't figure out where the error was.
I ended up "fixing" it by replacing the code with the one we'd working in Envoyer:
```php
<?php

namespace Deployer;

desc('Enable maintenance mode only if some migrations need to be run');
task('artisan:down_if_migrate', function () {
    $output = run('if ! {{bin/php}} {{release_path}}/artisan migrate:check ; then {{bin/php}} {{release_path}}/artisan down; fi');
    writeln("<info>$output</info>");
});
```

**Comment by lorisleiva** [comment]
This is weird because it is essentially the same code (regarding the if condition) but in your task you are running `php artisan down` on the `release_path` which should not be even visible at the stage (before migration anyways). This is why I was running it directly in the `current` folder.

**Comment by fgilio** [comment]
I forgot to say that I moved all this to the `done` hook, like this:
```php
        'done' => [
            'fpm:reload',
            'artisan:down_if_migrate',
            'artisan:migrate',
            'artisan:up',
            'artisan:horizon:terminate',
        ],
```

**Comment by lorisleiva** [comment]
Oh okay, it makes sense now. 🙂
