### ISSUE TITLE
Broken release sequence

### ISSUE THREAD

**Issue by forPelevin** [lorisleiva/laravel-deployer#37]
Hi.
First of all, I want to thank you for that laravel deployer. It's really cool :)

I faced with the strange behavior yesterday. When I run "php artisan deploy" (basic strategy), the new changes were deployed under release number 1, but I've already got 75 releases. How can I recover the release sequence? Thanks in advance!

**Comment by lorisleiva** [comment]
Hello 👋 

There is actually an option called `release_name` in charge of defining the name of the next release. So you could event configure that to be in a datetime format for example.

Here is what this option defaults to ([from Deployer](https://github.com/deployphp/deployer/blob/82f2c5d532565db16139b0746e48be483268ed4b/recipe/deploy/release.php#L12-L26)):

```php
set('release_name', function () {
    $list = get('releases_list');
    // Filter out anything that does not look like a release.
    $list = array_filter($list, function ($release) {
        return preg_match('/^[\d\.]+$/', $release);
    });
    $nextReleaseNumber = 1;
    if (count($list) > 0) {
        $nextReleaseNumber = (int)max($list) + 1;
    }
    return (string)$nextReleaseNumber;
}); // name of folder in releases
```

As you can see, by default, it reads all of the names of the existing releases (with numbers as names only) and takes the maximum plus one. If no releases (matching the number regex) were found in the `releases` folder, than it starts back at one.

I hope this helps 🤞

**Comment by forPelevin** [comment]
Hello!

Thank you. Now it makes sense. I found that the release number is wrong because my `releases_list` is empty. I saw it when called the `deploy:config` command. 

How can I recover the `releases_list`?

Thanks.

**Comment by lorisleiva** [comment]
Similarly to the `release_name` option, there is a `releases_list` option which default to a [relatively big function](https://github.com/deployphp/deployer/blob/82f2c5d532565db16139b0746e48be483268ed4b/recipe/deploy/release.php#L31-L81).

```php
set('releases_list', function () {
    cd('{{deploy_path}}');

    // If there is no releases return empty list.
    if (!test('[ -d releases ] && [ "$(ls -A releases)" ]')) {
        return [];
    }

    // Will list only dirs in releases.
    $list = explode("\n", run('cd releases && ls -t -1 -d */'));

    // Prepare list.
    $list = array_map(function ($release) {
        return basename(rtrim(trim($release), '/'));
    }, $list);

    $releases = []; // Releases list.

    // Collect releases based on .dep/releases info.
    // Other will be ignored.

    if (test('[ -f .dep/releases ]')) {
        $keepReleases = get('keep_releases');
        if ($keepReleases === -1) {
            $csv = run('cat .dep/releases');
        } else {
            // Instead of `tail -n` call here can be `cat` call,
            // but on hosts with a lot of deploys (more 1k) it
            // will output a really big list of previous releases.
            // It spoils appearance of output log, to make it pretty,
            // we limit it to `n*2 + 5` lines from end of file (15 lines).
            // Always read as many lines as there are release directories.
            $csv = run("tail -n " . max(count($releases), ($keepReleases * 2 + 5)) . " .dep/releases");
        }

        $metainfo = Csv::parse($csv);

        for ($i = count($metainfo) - 1; $i >= 0; --$i) {
            if (is_array($metainfo[$i]) && count($metainfo[$i]) >= 2) {
                list(, $release) = $metainfo[$i];
                $index = array_search($release, $list, true);
                if ($index !== false) {
                    $releases[] = $release;
                    unset($list[$index]);
                }
            }
        }
    }

    return $releases;
});
```

It is pretty well documented so it shouldn't be too difficult to debug what is going on. If your release list returns an empty array, chances are the if statement `test('[ -f .dep/releases ]')` is returning `false` which would mean your `.dep/releases` file is missing. This file is used by Deployer to keep track of releases name using timestamps.

Let me know how you get on 🍀

**Comment by forPelevin** [comment]
I manually remove wrong releases from the `.dep/releases` and now everything works fine.
Thank you very much!
