### ISSUE TITLE
Laravel 5.4 Composer require issue

### ISSUE THREAD

**Issue by EngEryx** [lorisleiva/laravel-deployer#38]
Hi guys,

What could I be doing wrong? I tried rquiring the package in my laravel 5.4 package but I got this:
`
Using version ^0.2.3 for lorisleiva/laravel-deployer
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for lorisleiva/laravel-deployer ^0.2.3 -> satisfiable by lorisleiva/laravel-deployer[v0.2.3].
    - Conclusion: remove laravel/framework v5.4.36
    - Conclusion: don't install laravel/framework v5.4.36
    - lorisleiva/laravel-deployer v0.2.3 requires illuminate/support 5.5.*|5.6.* -> satisfiable by illuminate/support[v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28, v5.5.33, v5.5.34, v5.5.35, v5.5.36, v5.5.37, v5.5.39, v5.5.40, v5.5.41, v5.6.0, v5.6.1, v5.6.10, v5.6.11, v5.6.12, v5.6.13, v5.6.14, v5.6.15, v5.6.16, v5.6.17, v5.6.19, v5.6.2, v5.6.20, v5.6.21, v5.6.22, v5.6.23, v5.6.24, v5.6.25, v5.6.26, v5.6.27, v5.6.28, v5.6.29, v5.6.3, v5.6.4, v5.6.5, v5.6.6, v5.6.7, v5.6.8, v5.6.9].
    - don't install illuminate/support v5.5.0|don't install laravel/framework v5.4.36
    - don't install illuminate/support v5.5.16|don't install laravel/framework v5.4.36
    - don't install illuminate/support v5.5.17|don't install laravel/framework v5.4.36
    - don't install illuminate/support v5.5.2|don't install laravel/framework v5.4.36
    - don't install illuminate/support v5.5.28|don't install laravel/framework v5.4.36
    - don't install illuminate/support v5.5.33|don't install laravel/framework v5.4.36
    - don't install illuminate/support v5.5.34|don't install laravel/framework v5.4.36
    - don't install illuminate/support v5.5.35|don't install laravel/framework v5.4.36
    - don't install illuminate/support v5.5.36|don't install laravel/framework v5.4.36
    - don't install illuminate/support v5.5.37|don't install laravel/framework v5.4.36
    - don't install illuminate/support v5.5.39|don't install laravel/framework v5.4.36
    - don't install illuminate/support v5.5.40|don't install laravel/framework v5.4.36
    - don't install illuminate/support v5.5.41|don't install laravel/framework v5.4.36
    - don't install illuminate/support v5.6.0|don't install laravel/framework v5.4.36
    - don't install illuminate/support v5.6.1|don't install laravel/framework v5.4.36
    - illuminate/support v5.6.10 conflicts with laravel/framework[v5.4.36].
    - illuminate/support v5.6.11 conflicts with laravel/framework[v5.4.36].
    - illuminate/support v5.6.12 conflicts with laravel/framework[v5.4.36].
    - illuminate/support v5.6.13 conflicts with laravel/framework[v5.4.36].
    - illuminate/support v5.6.14 conflicts with laravel/framework[v5.4.36].
    - illuminate/support v5.6.15 conflicts with laravel/framework[v5.4.36].
    - illuminate/support v5.6.16 conflicts with laravel/framework[v5.4.36].
    - illuminate/support v5.6.17 conflicts with laravel/framework[v5.4.36].
    - illuminate/support v5.6.19 conflicts with laravel/framework[v5.4.36].
    - don't install illuminate/support v5.6.2|don't install laravel/framework v5.4.36
    - illuminate/support v5.6.20 conflicts with laravel/framework[v5.4.36].
    - illuminate/support v5.6.21 conflicts with laravel/framework[v5.4.36].
    - illuminate/support v5.6.22 conflicts with laravel/framework[v5.4.36].
    - illuminate/support v5.6.23 conflicts with laravel/framework[v5.4.36].
    - illuminate/support v5.6.24 conflicts with laravel/framework[v5.4.36].
    - illuminate/support v5.6.25 conflicts with laravel/framework[v5.4.36].
    - illuminate/support v5.6.26 conflicts with laravel/framework[v5.4.36].
    - illuminate/support v5.6.27 conflicts with laravel/framework[v5.4.36].
    - illuminate/support v5.6.28 conflicts with laravel/framework[v5.4.36].
    - illuminate/support v5.6.29 conflicts with laravel/framework[v5.4.36].
    - don't install illuminate/support v5.6.3|don't install laravel/framework v5.4.36
    - don't install illuminate/support v5.6.4|don't install laravel/framework v5.4.36
    - don't install illuminate/support v5.6.5|don't install laravel/framework v5.4.36
    - don't install illuminate/support v5.6.6|don't install laravel/framework v5.4.36
    - don't install illuminate/support v5.6.7|don't install laravel/framework v5.4.36
    - illuminate/support v5.6.8 conflicts with laravel/framework[v5.4.36].
    - illuminate/support v5.6.9 conflicts with laravel/framework[v5.4.36].
    - Installation request for laravel/framework == 5.4.36.0 -> satisfiable by laravel/framework[v5.4.36].

Installation failed, reverting ./composer.json to its original content.
`

Should I upgrade my laravel app or which laravel-deployer version should I use?

Cheers!

**Comment by EngEryx** [comment]
Solved it ... thanks

used: composer global require lorisleiva/laravel-deployer

**Comment by lorisleiva** [comment]
Hi there 👋 

I'm afraid Laravel Deployer requires at least **Laravel 5.5**.

You should therefore upgrade to the next version and everything should work fine. 🙂

**Comment by EngEryx** [comment]
@lorisleiva  Thanks buddy

**Comment by ljonny18** [comment]
I'm having this issue with Laravel Framework 5.5.49

**Comment by lorisleiva** [comment]
Hi there 👋 

That’s because now, Laravel Deployer supports Laravel 5.8 and above.

**Comment by ljonny18** [comment]
ah thanks :) I will update and try again !!!
