### ISSUE TITLE
Change current directory

### ISSUE THREAD

**Issue by Sogl** [lorisleiva/laravel-deployer#39]
Hello!

How to change `current` dir to `public_html`?
I can't use another in my shared hosting.

**Comment by nemhal** [comment]
Depending on the hosting - you could make a symlink...

**Comment by lorisleiva** [comment]
Hi there 👋 

I've never had to do that myself so I'm not sure how reliable this solution is but there is an option called `current_path` that you can configure.

#### Option `current_path` ([full code from Deployer](https://github.com/deployphp/deployer/blob/82f2c5d532565db16139b0746e48be483268ed4b/recipe/common.php#L96-L99))

By default this option is defined like this:

```php
set('current_path', function () {
    $link = run("readlink {{deploy_path}}/current");
    return substr($link, 0, 1) === '/' ? $link : get('deploy_path') . '/' . $link;
});
```

So you would need to override this option by changing `current` to `public_html`.

**Moreover**, there are a lot of tasks that rely on the current directory being called `current`. all of these tasks will need to be adjusted as well. I have done a quick scan in Deploy's tasks and it looks like the tasks `deploy:prepare` and `deploy:symlink` are one of them.

---

#### Task `deploy:prepare` ([full code from Deployer](https://github.com/deployphp/deployer/blob/82f2c5d532565db16139b0746e48be483268ed4b/recipe/deploy/prepare.php#L12-L39))

Here is the part of the code that needs to be updated:

```php
// Check for existing /current directory (not symlink)
$result = test('[ ! -L {{deploy_path}}/current ] && [ -d {{deploy_path}}/current ]');
if ($result) {
    throw new \RuntimeException('There already is a directory (not symlink) named "current" in ' . get('deploy_path') . '. Remove this directory so it can be replaced with a symlink for atomic deployments.');
```

---

#### Task `deploy:symlink` ([full code from Deployer](https://github.com/deployphp/deployer/blob/ede141ed3ecbba097702fb99723f6a728b16efbf/recipe/deploy/symlink.php#L10-L21))

```php
task('deploy:symlink', function () {
    if (get('use_atomic_symlink')) {
        run("mv -T {{deploy_path}}/release {{deploy_path}}/current");
    } else {
        // Atomic symlink does not supported.
        // Will use simple≤ two steps switch.
        run("cd {{deploy_path}} && {{bin/symlink}} {{release_path}} current"); // Atomic override symlink.
        run("cd {{deploy_path}} && rm release"); // Remove release link.
    }
});
```

---

Also if you want to be able to rollback to previous releases, you'll have to update the `rollback` task ([full code from Deployer](https://github.com/deployphp/deployer/blob/ede141ed3ecbba097702fb99723f6a728b16efbf/recipe/deploy/rollback.php)).

As you can see the magic word `current` is pretty much everywhere in Deployer so it is a bit of a hack to use a different folder structure. Nevertheless if you wish to go on with this you might want to read this documentation that explains [how to include your own recipes and create (and override) your own task](https://github.com/lorisleiva/laravel-deployer/blob/15e92ea529fc55557dc51bebf609202c5246a3ba/docs/how-to-custom-recipes.md).

I hope this helps. Good luck in this adventure. 🍀
