### ISSUE TITLE
Can't detect http user name

### ISSUE THREAD

**Issue by sweebee** [lorisleiva/laravel-deployer#4]
```
In writable.php line 30:
                                              
  Can't detect http user name.                
  Please setup `http_user` config parameter.  
```

How can I set this?

**Comment by lorisleiva** [comment]
Hello, you have an option called `http_user`. Just like any option you can either set it up globally:

```php
```

**Comment by lorisleiva** [comment]
Hello, you have an option called `http_user`. Just like any other option you can set it up in your `deploy.php` globally:

```php
set('http_user', 'sweebee');
```

Or locally within a specific host:

```php
host('your.domain.com')
    ->set('http_user', 'sweebee');
```

You can check all available options and their default value [here](https://github.com/lorisleiva/laravel-deployer/blob/master/docs/all-options.md).
