### ISSUE TITLE
Response code when host is not found is still 0

### ISSUE THREAD

**Issue by tomneedham** [lorisleiva/laravel-deployer#41]
For scripting / CI it would be nice if the response code was non-zero:

<img width="973" alt="screen shot 2018-08-15 at 21 05 39" src="https://user-images.githubusercontent.com/660805/44170381-1b360680-a0cf-11e8-8e8f-ea63fd934ab9.png">

**Comment by tomneedham** [comment]
In fact, in general, I find the exit code is not returned, and it is always 0 in this wrapper

**Comment by tomneedham** [comment]
Fixed here https://github.com/lorisleiva/laravel-deployer/pull/42

**Comment by lorisleiva** [comment]
Hi 👋 

I've had the same problem when using GitLab's pipelines and something failed. It's been on my To-Do list for a while now. Thank you very much for the PR!
