### ISSUE TITLE
 How can I add a composer task ?

### ISSUE THREAD

**Issue by ken-sayama** [lorisleiva/laravel-deployer#44]
Hi @lorisleiva !
Thank you for making this package!

I don't know how to configration add task for composer.
If I want to add build task "composer install --no-dev" what should I do ?

**Comment by lorisleiva** [comment]
Hi there 👋 

There are two options that you can use to control the behaviour of composer. You can override them in your `config/deploy.php` file like so (these are the default value):

```php
'options' => [
    'composer_action' => 'install',
    'composer_options' => '{{composer_action}} --verbose --prefer-dist --no-progress --no-interaction --no-dev --optimize-autoloader',
]
```

In your case, you can simply override the `composer_options` and remove the `--no-dev` flag.

```php
'options' => [
    'composer_options' => '{{composer_action}} --verbose --prefer-dist --no-progress --no-interaction --optimize-autoloader',
]
```

You can find [all options and their default value](https://github.com/lorisleiva/laravel-deployer/blob/00ad2a2adb975f066bfb947ec245c1e59811633c/docs/all-options.md) in the documentation.

**Comment by ken-sayama** [comment]
@lorisleiva 
Thank you for reply!
