### ISSUE TITLE
Deployer should have an exit 0 signal for failed deployments

### ISSUE THREAD

**Issue by jiggsfoo** [lorisleiva/laravel-deployer#45]
Failed deployments should have an `exit 0` signal so the CI runner will know it failed.

My Gitlab deploy stage was failing but was still reporting success because of this. I only found out that the deploy was locked after I examined the build output.

**Comment by jiggsfoo** [comment]
I guess #42 fixes it. Sorry for the noise.

**Comment by lorisleiva** [comment]
Hi, yes that's correct, you just need to upgrade to the latest version ⬆️
