### ISSUE TITLE
Command "deploy" is not defined.

### ISSUE THREAD

**Issue by DMDc0de** [lorisleiva/laravel-deployer#49]
Right after issueing `composer require lorisleiva/laravel-deployer` from the root of my laravel project, if I try `php artisan deploy` i get `Command "deploy" is not defined`.
The composer installations finishes without errors and I can see a `loreisleva` folder inside my `vendors`.
Output of `php artisan --version`:
Laravel Framework 5.6.7

**Comment by lorisleiva** [comment]
Hi, you need to run `php artisan deploy:init` to start configuring your deployment process before you can deploy.

**Comment by DMDc0de** [comment]
Yes that's the command i gave
<img width="522" alt="schermata 2018-09-19 alle 17 01 34" src="https://user-images.githubusercontent.com/7113516/45762030-bcaffb00-bc2d-11e8-93ab-dc64fcd235a8.png">

```
White-2:apiato macbookpro15tb$ composer show | grep lorisleiva/laravel-deployer
lorisleiva/laravel-deployer           v0.2.5             Laravel Deployer is a lightweight wrapper of Deployer giving Artisan the power of zero-downtime deployment.

```

**Comment by lorisleiva** [comment]
Hmm that's odd. You wouldn't have something that disables Laravel's auto discovery of packages, would you? If so try to add the `Lorisleiva\LaravelDeployer\LaravelDeployerServiceProvider::class` into your `config/app.php`.

**Comment by DMDc0de** [comment]
Yes, I agree that's odd. It's a clean install of [apiato](http://apiato.io/), so maybe as you say there's something that disables Laravel's auto discovery of packages.
Adding `Lorisleiva\LaravelDeployer\LaravelDeployerServiceProvider::class` to the providers fixes the issue.
Thank you so much!
