### ISSUE TITLE
[solved] Can't find duplicate hostname with different stages

### ISSUE THREAD

**Issue by ivanvermeyen** [lorisleiva/laravel-deployer#5]
Hello

This is probably something from Deployer itself, but I just wanted to share this in case anyone else has this issue.

- I have one server with a production and a staging site on it.
- Both sites are behind CloudFlare, so you can't directly SSH into it.

Therefor I created an alias host in `~/.ssh/config` called `deploy.servername.com`, which connects directly to the server IP:

```
Host deploy.servername.com
  HostName 1.2.3.4
  Port 22
  IdentitiesOnly yes
  IdentityFile ~/.ssh/id_rsa
```

So my deploy script looked like this:

```php
set('default_stage', 'staging');

host('deploy.servername.com')
    ->stage('production')
    ->set('deploy_path', '/home/forge/www.servername.com')
    ->set('keep_releases', 2)
    ->user('forge');

host('deploy.servername.com')
    ->stage('staging')
    ->set('deploy_path', '/home/forge/staging.servername.com')
    ->set('keep_releases', 2)
    ->user('forge');
```

Deploying to the  default host (staging) worked, but when I ran `php artisan deploy production` I got this error:

```
 [Deployer\Exception\Exception]
  Hostname or stage `production` was not found.
```

The fix was really simple tho.
I just created two hosts in `~/.ssh/config`:

```
Host servername.com
  HostName 1.2.3.4
  Port 22
  IdentitiesOnly yes
  IdentityFile ~/.ssh/id_rsa

Host staging.servername.com
  HostName 1.2.3.4
  Port 22
  IdentitiesOnly yes
  IdentityFile ~/.ssh/id_rsa
```

And now my deploy script looks like this:

```php
set('default_stage', 'staging');

host('servername.com')
    ->stage('production')
    ->set('deploy_path', '/home/forge/www.servername.com')
    ->set('keep_releases', 2)
    ->user('forge');

host('staging.servername.com')
    ->stage('staging')
    ->set('deploy_path', '/home/forge/staging.servername.com')
    ->set('keep_releases', 2)
    ->user('forge');
```

Now it works fine. 👍

**Comment by lorisleiva** [comment]
Thank you for sharing this. It looks like your ssh configs needs to match your deploy hosts. I wonder if it would also work if you just put the server's IP address on both deploy hosts directly. I think deployer supports that. 

Anyway, if more people come across this situation, I'll add all of that in the documentation. Thanks again.

**Comment by ivanvermeyen** [comment]
I don't think using the IP in the deploy script would work in my case, since both stages use the same IP. I would probably get the same issue as when I used the same hostname.

**Comment by lorisleiva** [comment]
Argh okay, good to know.
