### ISSUE TITLE
Problems with .env

### ISSUE THREAD

**Issue by daylaborers** [lorisleiva/laravel-deployer#50]
Hi,

the .env file is linked by deployer in the current path from .env -> ../../shared/.env. I edit the .env file, but Laravel doesn't have this changes. For example i make in tinker an env('MYCONFIG'); i get an null and not the value. What do i wrong?

Cheers
Ralf

**Comment by lorisleiva** [comment]
Hi there 👋 

By default, you should have the artisan command `config:cache` in your deployment process. Which means that you need to flush the cache after editing your `.env` file.

You can simply deploy again or run `php artisan config:cache` directly from your server (run `php artisan ssh` to connect directly into your `current` folder).

**Comment by daylaborers** [comment]
Hi,

this doesn't work:
```
admin@krypto:/var/www/stage/current$ tail .env
QUEUE_DRIVER=sync

CLIENT_ID=xxxxx
CLIENT_SECRET=xxxxxx
```
then:
```
php artisan config:cache
Configuration cache cleared!
Configuration cached successfully!

php artisan tinker
Psy Shell v0.9.8 (PHP 7.1.20-1+0~20180725103117.2+jessie~1.gbpd5b650 — cli) by Justin Hileman
>>> env('CLIENT_ID');
=> null
```

**Comment by lorisleiva** [comment]
That’s the expected behavior of `config:cache`. The `env()` function will always return `null` when used outside the configuration files. Please read [this section of the Laravel documentation](https://laravel.com/docs/5.7/configuration#configuration-caching) (especially the red note).

**Comment by daylaborers** [comment]
Ah Fuck, you are right. I don't read this. Shame on me. Thanks for your support
