### ISSUE TITLE
PHP Fatal error:  require(): Failed opening required '/var/www/myawesomeprojekt.de/releases/1/vendor/autoload.php'

### ISSUE THREAD

**Issue by MilanVieth** [lorisleiva/laravel-deployer#51]
There is no vendor directory in my projekt. If i generate it on the server directly and rerun artisan deploy it will be deleted...

**Comment by lorisleiva** [comment]
Hi there 👋 

I’m not sure to understand your issue. Could you explain me what is happening versus the expected behavior? Also could you please provide the content of your `config/deploy.php` file?

**Comment by lorisleiva** [comment]
Closed due to inactivity
