### ISSUE TITLE
Start Horizon

### ISSUE THREAD

**Issue by daylaborers** [lorisleiva/laravel-deployer#54]
Hey there,

i write the following receipe:
```
desc('Run Laravel Horizon');
task('artisan:horizon', function () {
    run('{{bin/php}} {{release_path}}/artisan horizon');
})->once();
```
When i deploy, horizon started, but deployer don't stop, i think he is waiting for the end of the artisan command. How can i do this, that horizon started and deployer finish?

Cheers
Ralf

**Comment by fgilio** [comment]
A common approach is to have something like http://supervisord.org/ be in charge of keeping Horizon working and then using `horizon:terminate` when deploying.
This is super easy if you are managing servers with https://forge.laravel.com

**Comment by lorisleiva** [comment]
Agreed. You should not start horizon within your deployment process but rather use `horizon:terminate` to refresh it.

Thanks @fgilio for providing useful links 👍
