### ISSUE TITLE
Php-fpm is in a docker container

### ISSUE THREAD

**Issue by asakurayoh** [lorisleiva/laravel-deployer#56]
Hi.
My php-fpm is in a docker container. When trying to deploy, it use which php to determine where php is and exit on error... Is there a way to configure how to handle PHP task? (Use the docker)

Thanks

**Comment by lorisleiva** [comment]
Hi 👋 

I think you might be looking for the `bin/php` option ([see doc](https://github.com/lorisleiva/laravel-deployer/blob/87fc912eb4908b0a472aefb8f076bc30926d70dd/docs/all-options.md)) that lets you provide the php binary you want to use.

Does that fix your issue?
