### ISSUE TITLE
dynamic release_path as upload_path

### ISSUE THREAD

**Issue by karneaud** [lorisleiva/laravel-deployer#57]
If I am building releases on my local machine and want to use the upload task to deploy to the host would the `upload_path` be translated to the "release" if I used `upload_path=>"dist/{{release_path}}"` ??

**Comment by lorisleiva** [comment]
Hi there 👋 

The `upload_path` is a local path whereas the `release_path` is dynamically computed for every hosts your want to deploy to. Therefore this would be invalid. Here is the code that performs the upload from your local machine to you hosts.

https://github.com/lorisleiva/laravel-deployer/blob/aa5ef4b40f9f002ed7417312dc0a24de8a37b233/src/strategy/upload.php#L54

Could I ask what deployment flow you are trying to achieve? We might be able to do this another way.

**Comment by karneaud** [comment]
@lorisleiva Well its sort of a combination of the two. I'm compiling releases on the local then uploading to remote. However, I'm noticing there are some hiccups in between so I'm trying to break them into two( or more) strategies so I don't have to start over

**Comment by lorisleiva** [comment]
What kind of hiccups are you talking about? If you're writing your own tasks and you want them to act on your machine instead of your hosts you should add the `->local()` to your task definition.

Here is an example:

https://github.com/lorisleiva/laravel-deployer/blob/aa5ef4b40f9f002ed7417312dc0a24de8a37b233/src/strategy/local.php#L60

**Comment by karneaud** [comment]
@lorisleiva hiccups that i do not hink involves the library itself but maybe the setup. I get a lot of `"deploy:failed"` sue to file permission issues from local to remote. I think ti could be because of my access permissions but in the event they do happen I want to sort off "pick up where I left off"

**Comment by lorisleiva** [comment]
Indeed, it looks like your server is not allowing Laravel Deployer to even access your `deploy_path`.

Not much Laravel Deployer can do for you until you resolve these permission issues.

**Comment by karneaud** [comment]
@lorisleiva very good work with this module though.... KUDOS!!!!

**Comment by lorisleiva** [comment]
Thanks! ☺️
