### ISSUE TITLE
First Deploy Error

### ISSUE THREAD

**Issue by moskoweb** [lorisleiva/laravel-deployer#59]
Hello,

I'm testing the package, however since the first deploy, even with a new Laravel, unchanged, return the same error every time.

What do I need to do to use the package?

```
Exception trace:

  1   Symfony\Component\Process\Process::mustRun(Object(Closure))
      /laravel/vendor/lorisleiva/laravel-deployer/src/LaravelDeployer/Commands/BaseCommand.php:110

  2   Lorisleiva\LaravelDeployer\Commands\BaseCommand::process("vendor/bin/dep --file=vendor/lorisleiva/laravel-deployer/.build/deploy.php deploy ")
      /laravel/vendor/lorisleiva/laravel-deployer/src/LaravelDeployer/Commands/BaseCommand.php:58
```

**Comment by lorisleiva** [comment]
Hi there 👋 

Could you please show the entire error message? This is not enough for me to see what is wrong.

Could you also please list all of the steps necessary to reproduce this error?

**Comment by moskoweb** [comment]
Hello, in case you only displayed this, after running ```php artisan deploy``` for the first time.

**Comment by lorisleiva** [comment]
* Did you set up your deployment flow by running `php artisan deploy:init` followed by checking the generated configuration file?
* Could you copy/paste the entire output of `php artisan deploy -vvv`?

**Comment by andrewo0** [comment]
Hi getting the same error<pre>
Error Output:
================


  at /Users/aosenga/spork/Newsletter/vendor/symfony/process/Process.php:223
    219|      */
    220|     public function mustRun(callable $callback = null, array $env = array())
    221|     {
    222|         if (0 !== $this->run($callback, $env)) {
  > 223|             throw new ProcessFailedException($this);
    224|         }
    225| 
    226|         return $this;
    227|     }

  Exception trace:

  1   Symfony\Component\Process\Process::mustRun(Object(Closure))
      /Users/aosenga/spork/Newsletter/vendor/lorisleiva/laravel-deployer/src/LaravelDeployer/Commands/BaseCommand.php:110

  2   Lorisleiva\LaravelDeployer\Commands\BaseCommand::process("vendor/bin/dep --file=vendor/lorisleiva/laravel-deployer/.build/deploy.php config:dump --verbose -v")
      /Users/aosenga/spork/Newsletter/vendor/lorisleiva/laravel-deployer/src/LaravelDeployer/Commands/BaseCommand.php:58

  3   Lorisleiva\LaravelDeployer\Commands\BaseCommand::dep("config:dump")
      /Users/aosenga/spork/Newsletter/vendor/lorisleiva/laravel-deployer/src/LaravelDeployer/Commands/DeployConfigs.php:12

  4   Lorisleiva\LaravelDeployer\Commands\DeployConfigs::handle()
      /Users/aosenga/spork/Newsletter/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:29

  5   call_user_func_array([])
      /Users/aosenga/spork/Newsletter/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:29

  6   Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
      /Users/aosenga/spork/Newsletter/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:87

  7   Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Object(Closure))
      /Users/aosenga/spork/Newsletter/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:31

  8   Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), [])
      /Users/aosenga/spork/Newsletter/vendor/laravel/framework/src/Illuminate/Container/Container.php:572

  9   Illuminate\Container\Container::call()
      /Users/aosenga/spork/Newsletter/vendor/laravel/framework/src/Illuminate/Console/Command.php:183

  10  Illuminate\Console\Command::execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
      /Users/aosenga/spork/Newsletter/vendor/symfony/console/Command/Command.php:255

  11  Symfony\Component\Console\Command\Command::run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
      /Users/aosenga/spork/Newsletter/vendor/laravel/framework/src/Illuminate/Console/Command.php:170

  12  Illuminate\Console\Command::run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
      /Users/aosenga/spork/Newsletter/vendor/symfony/console/Application.php:886

  13  Symfony\Component\Console\Application::doRunCommand(Object(Lorisleiva\LaravelDeployer\Commands\DeployConfigs), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
      /Users/aosenga/spork/Newsletter/vendor/symfony/console/Application.php:262

  14  Symfony\Component\Console\Application::doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
      /Users/aosenga/spork/Newsletter/vendor/symfony/console/Application.php:145

  15  Symfony\Component\Console\Application::run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
      /Users/aosenga/spork/Newsletter/vendor/laravel/framework/src/Illuminate/Console/Application.php:89

  16  Illuminate\Console\Application::run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
      /Users/aosenga/spork/Newsletter/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php:122

  17  Illuminate\Foundation\Console\Kernel::handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
      /Users/aosenga/hearst_nl/Newsletter/artisan:37
</pre>

**Comment by lorisleiva** [comment]
Weird the error output really does not provide much information. What version of Laravel Deployer are you using?

**Comment by andrewo0** [comment]
Just pulled in to my project

**Comment by andrewo0** [comment]
@lorisleiva Could it be that tasks are required to be filled in the config file and every time you de a deploy command it's trying to call the task array but failing because there are no tasks?

**Comment by lorisleiva** [comment]
@andrewo0 Can I have more information because I cannot reproduce this issue? Can you please provide me with the following:
* Which operating system?
* Which version of Laravel Deployer (please check the `composer.lock` file)?
* The content of your `config/deploy.php` file

**Comment by andrewo0** [comment]
Hi @lorisleiva i'm on a MAC .
Version Laravel deployer version v0.2.5

<pre>

return [

    /*
    |--------------------------------------------------------------------------
    | Default deployment strategy
    |--------------------------------------------------------------------------
    |
    | This option defines which deployment strategy to use by default on all
    | of your hosts. Laravel Deployer provides some strategies out-of-box
    | for you to choose from explained in detail in the documentation.
    |
    | Supported: 'basic', 'firstdeploy', 'local', 'pull'.
    |
    */

    'default' => 'basic',

    /*
    |--------------------------------------------------------------------------
    | Custom deployment strategies
    |--------------------------------------------------------------------------
    |
    | Here, you can easily set up new custom strategies as a list of tasks.
    | Any key of this array are supported in the `default` option above.
    | Any key matching Laravel Deployer's strategies overrides them.
    |
    */

    'strategies' => [
        //
    ],

    /*
    |--------------------------------------------------------------------------
    | Hooks
    |--------------------------------------------------------------------------
    |
    | Hooks let you customize your deployments conveniently by pushing tasks 
    | into strategic places of your deployment flow. Each of the official
    | strategies invoke hooks in different ways to implement their logic.
    |
    */

    'hooks' => [
        // Right before we start deploying.
        'start' => [
            //
        ],
        
        // Code and composer vendors are ready but nothing is built.
        'build' => [
            'npm:install',
            'npm:production',
        ],
        
        // Deployment is done but not live yet (before symlink)
        'ready' => [
            'artisan:storage:link',
            'artisan:view:clear',
            'artisan:cache:clear',
            'artisan:config:cache',
            'artisan:migrate',
        ],
        
        // Deployment is done and live
        'done' => [
            //
        ],
        
        // Deployment succeeded.
        'success' => [
            //
        ],
        
        // Deployment failed.
        'fail' => [
            //
        ],
    ],

    /*
    |--------------------------------------------------------------------------
    | Deployment options
    |--------------------------------------------------------------------------
    |
    | Options follow a simple key/value structure and are used within tasks
    | to make them more configurable and reusable. You can use options to
    | configure existing tasks or to use whithin your own custom tasks.
    |
    */

    'options' => [
        'application' => env('APP_NAME', 'Laravel'),
        'repository' => 'git@github.com:andrewo0/Newsletter.git',
    ],

    /*
    |--------------------------------------------------------------------------
    | Hosts
    |--------------------------------------------------------------------------
    |
    | Here, you can define any domain or subdomain you want to deploy to.
    | You can provide them with roles and stages to filter them during
    | deployment. Read more about how to configure them in the docs.
    |
    */

    'hosts' => [
        'newsletter.andrewosenga.nl' => [
            'deploy_path' => '/var/www/newsletter.andrewosenga.nl',
            'user' => 'root',
        ],
    ],

    /*
    |--------------------------------------------------------------------------
    | Localhost
    |--------------------------------------------------------------------------
    |
    | This localhost option give you the ability to deploy directly on your
    | local machine, without needing any SSH connection. You can use the
    | same configurations used by hosts to configure your localhost.
    |
    */

    'localhost' => [
        //
    ],

    /*
    |--------------------------------------------------------------------------
    | Include additional Deployer recipes
    |--------------------------------------------------------------------------
    |
    | Here, you can add any third party recipes to provide additional tasks, 
    | options and strategies. Therefore, it also allows you to create and
    | include your own recipes to define more complex deployment flows.
    |
    */

    'include' => [
        //
    ],

    /*
    |--------------------------------------------------------------------------
    | Use a custom Deployer file
    |--------------------------------------------------------------------------
    |
    | If you know what you are doing and want to take complete control over
    | Deployer's file, you can provide its path here. Note that, without
    | this configuration file, the root's deployer file will be used.
    |
    */

    'custom_deployer_file' => false,

];

</pre>

**Comment by lorisleiva** [comment]
Thanks! Soooo we basically have the same configurations haha.

I've juste tried on a fresh Laravel install and it works as expected:

```bash
laravel new dummy_app
cd dummy_app
composer require lorisleiva/laravel-deployer
php artisan deploy:init -a
php artisan deploy:list # works
```

**Comment by andrewo0** [comment]
and if you try
<pre>
php artisan deploy:configs
</pre>

**Comment by lorisleiva** [comment]
Based on your provided Exception trace `deploy:list` should not work either. Can you please try and show me the output?

**Comment by andrewo0** [comment]
found the issue was missing my deploy key on git thanks for the help @lorisleiva

**Comment by lorisleiva** [comment]
No problem, thanks for reporting this.
