### ISSUE TITLE
Question: Is SSH required ?

### ISSUE THREAD

**Issue by sarfraznawaz2005** [lorisleiva/laravel-deployer#6]
Thanks for nice project!

Does it work for shared hosting eg what if I only have ftp/sftp details but not SSH ?

Thanks

**Comment by lorisleiva** [comment]
Hello, I am glad you like it.

Unfortunately, Laravel Deployer only works via SSH since it has to execute commands on the hosts you defined.

Laravel Deployer is using Deployer.org behind the scenes which [does not support FTP](https://github.com/deployphp/deployer/issues/458).
