### ISSUE TITLE
{{bin/yarn}} missing

### ISSUE THREAD

**Issue by neolikotsi** [lorisleiva/laravel-deployer#64]
HI  there

After I installed the package in a laravel 5.7,  `composer require lorisleiva/laravel-deployer`, 
I traversed the package dir under `vendors/lorisleiva/laravel-deployer/src/task`
`yarn.php` is missing 
and
the file `vendors/lorisleiva/laravel-deployer/src/recipe/laravel-deployer.php` missing ln 27 
as in #52(issue) #55(pr fix)

**Comment by lorisleiva** [comment]
Hi there 👋 

Yes this is normal as the yarn addition has been developed but not published yet. I wanted to test it manually before tagging a new release but haven't had the time recently. If you could upgrade to `dev-master` and check for me that it all works fine that would be very helpful 🙂

**Comment by neolikotsi** [comment]
resolved in release v0.2.6
