### ISSUE TITLE
Files And Directory  Permissions

### ISSUE THREAD

**Issue by BenQoder** [lorisleiva/laravel-deployer#65]
I have this bug or error where I have to fix my files and directory permissions each time I deploy.

In summary my files and directories changes permissions after each deployment

**Comment by neolikotsi** [comment]
I experienced the same issue because my ssh user is `root` but my app web user is a `www-data`. 
In solution to my problem I inject my own task to change file and dir permissions

in `deploy.php`

```
 ... omitted ...
'ready' => [
 ... omtted ...
    'app:permissions',
],
...
'options' => [ 
   'app_user' => 'www-data',
],

'include' => [
     'path/to/tasks.php',
 ],
```

then my `tasks.php`

```
<?php

namespace Deployer;

desc('Change app:permissions');
task('app:permissions', function () {
    writeln('change permissions to {{app_user}} in {{release_path}}');
    run('cd {{deploy_path}}/shared && chown -Rf {{app_user}}:{{app_user}} storage');
    run('cd {{release_path}} && chown -Rf {{app_user}}:{{app_user}} storage bootstrap && chown -Rf {{app_user}}:{{app_user}} public/*');
});
```

**Comment by BenQoder** [comment]
The solution that worked for me was

```php
<?php 
namespace Deployer;
desc('Change Files And Folder Permissions');
task('app:permissions', function () {
	run('find {{deploy_path}} -type d -exec chmod 0755 {} +');
	run('find {{deploy_path}} -type f -exec chmod 0644 {} +');
});
```

in my tasks.php

**Comment by neolikotsi** [comment]
Great @BenQoder! After each successful deploy you have to set the correct permissions - see
[(https://laracasts.com/discuss/channels/general-discussion/laravel-framework-file-permission-security )]

**Comment by lorisleiva** [comment]
Hi there 👋 

Thanks for providing your solution with supporting links.

Quick question before I close this: what happens if you set your `http_user` option directly to `www-data`? Do you still need the `app:permissions` custom task?

**Comment by neolikotsi** [comment]
Hi there!

In my case, setting the `http_user` does not solve the problem that the custom task `app:permissions` resolved.

The deployed files and dirs are owned by `root` user instead of `www-data`.

**Comment by lorisleiva** [comment]
Okay thanks for letting me know 👌

**Comment by callect** [comment]
I have same issue.Have any PR merge into master code , or any other solution?

**Comment by simonbuehler** [comment]
it would be great if this was incorporated into the default options, shouldn't

```
'options' => [
        'application' => env('APP_NAME', 'app'),
        'repository' => 'xxx',
        'writable_mode' => 'chown',
        'writable_dirs' => ['{{deploy_path}}']
    ],
```

work?
