### ISSUE TITLE
failed to deployed on host :ssh connection timed out

### ISSUE THREAD

**Issue by aymard229** [lorisleiva/laravel-deployer#67]
Am trying to deploy my laravel app to my hosting server. 
When I launch **php artisan deploy**, I have this :
### output
✈︎ Deploying feature on spoilerinter.com with basic9
m strategy
➤ Executing task deploy:prepare
➤ Executing task deploy:failed
✔
➤ Executing task deploy:unlock

### Error Output:

In Client.php line 99:
  The command "rm -f /public_html/.dep/deploy.lock" failed.

  Exit Code: -1 (Unknown error)

  Host Name: spoilerinter.com

  ================

  ssh: connect to host mydomain.com port 22: Connection timed out

**Comment by lorisleiva** [comment]
Hi there 👋 

Looks like your host is not responding to the SSH connection you defined in the `deploy.php` configuration file. I doubt this is an issue for Laravel Deployer itself.

**Comment by aymard229** [comment]
You're right @lorisleiva . It's was the bad ssh port.
Thanks for your time

**Comment by fgilio** [comment]
Arrived up here because of a similar problem. It ended up being a DNS cache issue related to a recent domain name change, I temporarily solved it by just using the IP instead of the domain.
Hope it helps if someone else ends up here :)
