### ISSUE TITLE
Hooks and Hosts

### ISSUE THREAD

**Issue by daylaborers** [lorisleiva/laravel-deployer#69]
Hi,

when i deploy on staging i want to use hooks => ready => artisan:db:seed. When i deploy on production i don't want make an seed.

Is it possible, to use different hooks for different hosts?

Cheers
Ralf

**Comment by lorisleiva** [comment]
Hi there 👋 

The only way you could achieve something like that at the moment is to create two different strategies and set up the `strategy` option for each host.

Would be good in the next versions of Laravel Deployer to support custom hooks and enable/disable them per hosts. Thanks for raising this issue.

**Comment by pixelplant** [comment]
This is something that we'd love to have since we're using 1 deploy.php file for our dev, staging and prod servers but which would need slightly different hooks to be called during deployment.

Any news on this request?

Thanks again for the great work
