### ISSUE TITLE
Clean up old releases?

### ISSUE THREAD

**Issue by Nowi5** [lorisleiva/laravel-deployer#74]
Hi,

just a quick question, how do you clean up old releases? Can I set somewhere, delete all releases older than... or just keep the last 3?

Thank you.

**Comment by lorisleiva** [comment]
👋 Hi there,

Releases are automatically cleaned up when the number of releases reaches a maximum. This maximum is set up as the `keep_releases` option (defaults to 5). If you do not wish to clean up releases you can set this up as `-1`.

You can see [all options available in the documentation](https://github.com/lorisleiva/laravel-deployer/blob/7fd18a30d4d44c4567dc25d865508aa74c9a9318/docs/all-options.md).

Hope this helps.
