### ISSUE TITLE
Artisan commands error

### ISSUE THREAD

**Issue by liranAtli** [lorisleiva/laravel-deployer#77]
Hello, 
guy's I have a critical problem,
when I deploy without artisan commands all works fine but when I add artisan's command I got an error all the time, someone has any idea for me?

my deploy.php

`<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Default deployment strategy
    |--------------------------------------------------------------------------
    |
    | This option defines which deployment strategy to use by default on all
    | of your hosts. Laravel Deployer provides some strategies out-of-box
    | for you to choose from explained in detail in the documentation.
    |
    | Supported: 'basic', 'firstdeploy', 'local', 'pull'.
    |
    */

    'default' => 'basic',

    /*
    |--------------------------------------------------------------------------
    | Custom deployment strategies
    |--------------------------------------------------------------------------
    |
    | Here, you can easily set up new custom strategies as a list of tasks.
    | Any key of this array are supported in the `default` option above.
    | Any key matching Laravel Deployer's strategies overrides them.
    |
    */

    'strategies' => [
        //
    ],

    /*
    |--------------------------------------------------------------------------
    | Hooks
    |--------------------------------------------------------------------------
    |
    | Hooks let you customize your deployments conveniently by pushing tasks 
    | into strategic places of your deployment flow. Each of the official
    | strategies invoke hooks in different ways to implement their logic.
    |
    */

    'hooks' => [
        // Right before we start deploying.
        'start' => [
            //
        ],
        
        // Code and composer vendors are ready but nothing is built.
        'build' => [
            //
        ],
        
        // Deployment is done but not live yet (before symlink)
        'ready' => [
            'artisan:storage:link',
            'artisan:view:clear',
            'artisan:cache:clear',
            'artisan:config:cache',
            'artisan:migrate',
        ],
        
        // Deployment is done and live
        'done' => [
            //
        ],
        
        // Deployment succeeded.
        'success' => [
            //
        ],
        
        // Deployment failed.
        'fail' => [
            //
        ],
    ],

    /*
    |--------------------------------------------------------------------------
    | Deployment options
    |--------------------------------------------------------------------------
    |
    | Options follow a simple key/value structure and are used within tasks
    | to make them more configurable and reusable. You can use options to
    | configure existing tasks or to use whithin your own custom tasks.
    |
    */

    'options' => [
        'application' => env('APP_NAME', 'Laravel'),
        'repository' => 'git@gitlab.com:touchngo/touchngo-backend.git',
    ],

    /*
    |--------------------------------------------------------------------------
    | Hosts
    |--------------------------------------------------------------------------
    |
    | Here, you can define any domain or subdomain you want to deploy to.
    | You can provide them with roles and stages to filter them during
    | deployment. Read more about how to configure them in the docs.
    |
    */

    'hosts' => [
        'touchngo.co.il' => [
            'deploy_path' => '/var/www/vhosts/touchngo.co.il',
            'user' => 'root',
            'identityFile' => '~/.ssh/id_rsa2',
            'forwardAgent' => true,
            'multiplexing' => true,
        ],
    ],

    /*
    |--------------------------------------------------------------------------
    | Localhost
    |--------------------------------------------------------------------------
    |
    | This localhost option give you the ability to deploy directly on your
    | local machine, without needing any SSH connection. You can use the
    | same configurations used by hosts to configure your localhost.
    |
    */

    'localhost' => [
        //
    ],

    /*
    |--------------------------------------------------------------------------
    | Include additional Deployer recipes
    |--------------------------------------------------------------------------
    |
    | Here, you can add any third party recipes to provide additional tasks, 
    | options and strategies. Therefore, it also allows you to create and
    | include your own recipes to define more complex deployment flows.
    |
    */

    'include' => [
        //
    ],

    /*
    |--------------------------------------------------------------------------
    | Use a custom Deployer file
    |--------------------------------------------------------------------------
    |
    | If you know what you are doing and want to take complete control over
    | Deployer's file, you can provide its path here. Note that, without
    | this configuration file, the root's deployer file will be used.
    |
    */

    'custom_deployer_file' => false,

];
`

**Comment by lorisleiva** [comment]
Hi there 👋 

Could you please share the error that you get using artisan tasks?

**Comment by liranAtli** [comment]
sure here all the scenario 

> ✈︎ Deploying master on touchngo.co.il with basic strategy
✔ Executing task deploy:prepare
✔ Executing task deploy:lock
✔ Executing task deploy:release
✔ Executing task deploy:update_code
✔ Executing task deploy:shared
✔ Executing task deploy:vendors
✔ Executing task deploy:writable
➤ Executing task artisan:storage:link
✔ Executing task deploy:failed
✔ Executing task deploy:unlock

In Client.php line 99:

  The command "/usr/bin/php /var/www/vhosts/touchngo.co.il/releases/1/artisan --version" failed.

  Exit Code: 255 (Unknown error)

  Host Name: touchngo.co.il

  ================
  PHP Warning:  require(/var/www/vhosts/touchngo.co.il/releases/1/vendor/autoload.php): failed to open stream: No such file or directory in /var/www/vhosts/touchngo.co.il/releases/1/artisan on li
  ne 18
  PHP Fatal error:  require(): Failed opening required '/var/www/vhosts/touchngo.co.il/releases/1/vendor/autoload.php' (include_path='.:/usr/share/php') in /var/www/vhosts/touchngo.co.il/releases
  /1/artisan on line 18

**Comment by lorisleiva** [comment]
This file `/var/www/vhosts/touchngo.co.il/releases/1/vendor/autoload.php` should exists as you're running the `deploy:vendors` task which basically runs `composer install`.

Can you please check that there isn't anything fishy with your composer installation on your server?

**Comment by liranAtli** [comment]
> Can you please check that there isn't anything fishy with your composer installation on your server?

you mean on composer.json ? before i do composer install?

**Comment by liranAtli** [comment]
### This is my composer.json

`{
    "name": "laravel/laravel",
    "description": "The Laravel Framework.",
    "keywords": [
        "framework",
        "laravel"
    ],
    "license": "MIT",
    "type": "project",
    "require": {
        "php": "^7.1.3",
        "ext-json": "*",
        "barryvdh/laravel-cors": "^0.11.2",
        "barryvdh/laravel-translation-manager": "^0.5.2",
        "bissolli/landlord": "master",
        "fideloper/proxy": "^4.0",
        "flugger/laravel-responder": "^3.0",
        "kblais/laravel-uuid": "^1.0",
        "laravel/framework": "5.7.*",
        "laravel/passport": "^7.0",
        "laravel/tinker": "^1.0",
        "lorisleiva/laravel-deployer": "^0.2.5",
        "plank/laravel-mediable": "^2.8",
        "silber/bouncer": "v1.0.0-rc.4",
        "tucker-eric/eloquentfilter": "^1.3",
        "vlucas/phpdotenv": "^2.5"
    },
    "require-dev": {
        "barryvdh/laravel-ide-helper": "^2.5",
        "beyondcode/laravel-dump-server": "^1.0",
        "filp/whoops": "^2.0",
        "fzaninotto/faker": "^1.4",
        "laravel/homestead": "^7.18",
        "mockery/mockery": "^1.0",
        "nunomaduro/collision": "^2.0",
        "phpunit/phpunit": "^7.0"
    },
    "autoload": {
        "classmap": [
            "database/seeds",
            "database/factories"
        ],
        "psr-4": {
            "App\\": "app/"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "Tests\\": "tests/"
        }
    },
    "extra": {
        "laravel": {
            "dont-discover": [
            ]
        }
    },
    "scripts": {
        "post-root-package-install": [
            "@php -r \"file_exists('.env') || copy('.env.example', '.env');\""
        ],
        "post-create-project-cmd": [
            "@php artisan key:generate --ansi"
        ],
        "post-autoload-dump": [
            "Illuminate\\Foundation\\ComposerScripts::postAutoloadDump",
            "@php artisan package:discover --ansi"
        ]
    },
    "config": {
        "preferred-install": "dist",
        "sort-packages": true,
        "optimize-autoloader": true
    },
    "minimum-stability": "dev",
    "prefer-stable": true
}
`

**Comment by liranAtli** [comment]
> Can you please check that there isn't anything fishy with your composer installation on your server?

what did you mean?

**Comment by liranAtli** [comment]
Ok, I have been solved the problem I needed to add on deploy.php file in 

>   'options' => [
        'application' => env('APP_NAME', 'Laravel'),
        **'bin/composer' => 'composer',**
        'composer_options' => 'install --verbose --prefer-dist --no-progress --no-interaction --optimize-autoloader',
    ],

this is fixed for me the error :)

**Comment by lorisleiva** [comment]
Great, thanks for sharing your solution 🙂
