### ISSUE TITLE
host can not use rsync

### ISSUE THREAD

**Issue by commentatorboy** [lorisleiva/laravel-deployer#85]
Hey I tried to use this wrapper to deploy to my shared host.
It currently does not work with any of the strategies. (Another issue is that the host uses old versions of npm and node, there I want to build everything locally).
So my question is. Is it possible to upload a builded configuration without using rsync?

**Comment by lorisleiva** [comment]
Hi there 👋 

- The `basic` strategy does not use `rsync` at all but you want to build locally.
- The `local` allows you to do that but uses `rsync` to upload.

To achieve what you want, you'll need to override the `local:upload` task which defaults to:

```php
desc('Upload your locally-built application to your hosts');
task('local:upload', function () {
    $configs = array_merge_recursive(get('local_upload_options'), [
        'options' => ['--delete']
    ]);
    upload('{{local_deploy_path}}/current/', '{{release_path}}', $configs);
});
```

The `upload` method comes directly from DeployerPHP and uses `rsync`. Therefore, you should replace it with the command of your choice using `run('...your command here...')`.

I hope this helps. Let me know how you get on. 🍀

**Comment by commentatorboy** [comment]
Hey thanks for the feedback.
I am currently trying to use deployerPHP.
And it kind of works.
In the deploy.php (for deployerPHP) you can set the writable_mode to be chmod.
`set('writable_mode', 'chmod');` (more about it can be seen here: [https://github.com/deployphp/deployer/issues/1118](link) )
This causes deployerPHP to not use acl, and almost everything works. 
The only thing I need is to setup the symlinks.

I am not too keen on servers, so I might not be able to solve it immediately.
But I guess if I can find the commands used when the writable_mode is set to chmod I could run it.
I will update, when I have more information.

**Comment by lorisleiva** [comment]
I'm not sure I understand your question. 😕

**Comment by commentatorboy** [comment]
You said that I should replace the `upload` method with `run('...your command here...')`.
But I do not know exactly what my command should be. (Since I am not experienced with servers).
So I was just trying to figure out what I should write.

**Comment by lorisleiva** [comment]
I see. I'm not sure what you can use on your server but probably something like `scp`.

This [issue from DeployerPHP](https://github.com/deployphp/deployer/issues/1369#issuecomment-387596072) shows you how to:

```php
runLocally("scp -rC -P {{port}} {$source} {{user}}@{{hostname}}:{{deploy_path}}/{$destination}");
```

Also, here's the code of the default `upload` function in case you need some inspiration: https://github.com/deployphp/deployer/blob/6e284828d703a4fcd0376a491be8fc71767e0255/src/functions.php#L426-L451

Closing this since it's not relevant to the core of Laravel Deployer.
Good luck 🍀
