### ISSUE TITLE
Different .env file for environments?

### ISSUE THREAD

**Issue by notflip** [lorisleiva/laravel-deployer#86]
Is this possible? I'm just learning about this repo, but I'm trying to setup a staging and production on the same server, the staging will have a different DB_DATABASE environment variable. Is it possible to achieve this? Since the .env file is shared by default?

**Comment by lorisleiva** [comment]
Hi there 👋 

Yes of course, there is a `shared` folder within each deployment directory. The environment file is only shared across the releases.

You just need to create two hosts with different `deploy_path`.

I hope this helps. 🍀

**Comment by notflip** [comment]
Thanks for the fast reply! Do I need to create a separate .env file per environment then? Or how do I decide which deploy_path get's which .env file?

**Comment by lorisleiva** [comment]
Yes exactly. Each host should have their own .env file. You just need to define two different `deploy_path` then in each of those folder you need to define your environment in `shared/.env`.

**Comment by lorisleiva** [comment]
Yes that’s right. There is no point adding this to the deploy strategy since it’s only a one-time thing to set up.

Have a look at the section “Set up your production environment” of the checklist of that article: https://lorisleiva.com/learn-laravel-deployer-1/

**Comment by notflip** [comment]
So I created the .env file in my /var/www/staging/shared/.env
Everything is setup as in the docs but I'm getting errors that show that the .env file isn't being used

for example: trying to connect to my database using default credentials (db_database: forge).
**Is there anything else I need to do besides having an .env file in the shared folder?**
