### ISSUE TITLE
Don't ask for ssh keys

### ISSUE THREAD

**Issue by mehrdaad** [lorisleiva/laravel-deployer#9]
Hi, Is there any way to pass ssh password when defining hosts?  
Also this question applies for when running ``upload`` command.

**Comment by lorisleiva** [comment]
I'm afraid the underlying deployment layer (Deployer.org) does not allow you to define a password in your configurations (e.g. [see this issue](https://github.com/deployphp/deployer/issues/1162)). It was design to connect via SSH keys.

**Comment by mehrdaad** [comment]
Also, I have another question but don't want to open another issue.  
How do you manage staging environment‌?  
By staging I mean an environment where ``.evn`` is almost as local.  We run phpunit and it fails we rollback deployment and we deploy only if tests pass.

**Comment by lorisleiva** [comment]
You can easily add a phpunit task and hook into into your deployment flow after everything has been built. I am currently working on a version v0.2 which should be more intuitive for laravel dev to get started and that will have those phpunit includes out the box. The only tricky thing with phpunit is that you will have to change the option `composer_options` to remove the `--no-dev` flag for the hosts of your choice.

**Comment by mehrdaad** [comment]
Or maybe move phpunit to ``require`` section?
