### ISSUE TITLE
New release not updating

### ISSUE THREAD

**Issue by ghidoz** [lorisleiva/laravel-deployer#91]
Hi, after many successful releases with the laravel-deployer, today something is not working anymore.
Even if the logs say that everything is ok and I can actually find the new release correctly symlinked on my server, when I browse my app I still see the old version.

My app is just an API service, so I notice that the old version is loading because the new endpoints I added don't exist.

My successful log:

```
Running with gitlab-runner 11.8.0 (4745a6f3)
  on docker-auto-scale fa6cab46
Using Docker executor with image lorisleiva/laravel-docker:latest ...
Pulling docker image lorisleiva/laravel-docker:latest ...
Using docker image sha256:4bd5ecacba7b0f46950944f376647090071a70a7b1ffa0eacb492719bd476c6b for lorisleiva/laravel-docker:latest ...
Running on runner-fa6cab46-project-9910367-concurrent-0 via runner-fa6cab46-srm-1551134133-4052c1d5...
Cloning repository...
Cloning into '/builds/ghido/whereismytribe'...
Checking out c0246411 as master...
Skipping Git submodules setup
Downloading artifacts for api-build (167405339)...
Downloading artifacts from coordinator... ok        id=167405339 responseStatus=200 OK token=Wqmh8kkv
$ eval $(ssh-agent -s)
Agent pid 10
$ echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
Identity added: (stdin) ((stdin))
$ mkdir -p ~/.ssh
$ chmod 700 ~/.ssh
$ ssh-keyscan [ip] >> ~/.ssh/known_hosts
# [ip]:22 SSH-2.0-OpenSSH_7.6p1 Ubuntu-4ubuntu0.2
# [ip]:22 SSH-2.0-OpenSSH_7.6p1 Ubuntu-4ubuntu0.2
# [ip]:22 SSH-2.0-OpenSSH_7.6p1 Ubuntu-4ubuntu0.2
$ cd api
$ php artisan deploy [ip] -s upload
✈︎ Deploying HEAD on [ip] with upload strategy
➤ Executing task deploy:prepare
✔ Ok
➤ Executing task deploy:lock
✔ Ok
➤ Executing task deploy:release
✔ Ok
➤ Executing task deploy:update_code
✔ Ok
➤ Executing task upload
✔ Ok
➤ Executing task deploy:shared
✔ Ok
➤ Executing task deploy:vendors
To speed up composer installation setup "unzip" command with PHP zip extension https://goo.gl/sxzFcD
✔ Ok
➤ Executing task deploy:writable
✔ Ok
➤ Executing task artisan:storage:link
✔ Ok
➤ Executing task artisan:view:clear
✔ Ok
➤ Executing task artisan:cache:clear
✔ Ok
➤ Executing task artisan:config:cache
✔ Ok
➤ Executing task artisan:migrate
✔ Ok
➤ Executing task deploy:symlink
✔ Ok
➤ Executing task deploy:unlock
✔ Ok
➤ Executing task cleanup
✔ Ok
🚀  Successfully deployed in 58.3s
Job succeeded
```

My symlink:
`current -> releases/9/`

Files in the /9/ folder are the new ones, but when I browse the app I still see the old endpoints.
Any ideas?

Thanks!

**Comment by MCMainiac** [comment]
Just here to say I'm experiencing the same problems when publishing new releases. The latest release is used when I delete the previous one.

In your case I would delete `releases/8/`

**Comment by lorisleiva** [comment]
Hi there 👋 

I've had this issue in the past as well and it was to do with the OPcache not detecting the changes in my PHP files. Could you please read the following troubleshooting section from the documentation and let me know if that fixes your issue?

[Troubleshooting: My changes don't show up after a deployment.](https://github.com/lorisleiva/laravel-deployer/blob/919ea8386308d86837f434b69f40529854d15082/docs/troubleshooting.md#my-changes-dont-show-up-after-a-deployment)

Thanks for reporting this.

**Comment by notflip** [comment]
Same issue just now! Fixed it by deleting the previous release.

    rm -rf releases/1

**Comment by MCMainiac** [comment]
I tried restarting php-fpm after releasing a new deployment and it seems to work. More information on how to restart here: [serverfault.com/a/189961](https://serverfault.com/a/189961)

**Comment by lorisleiva** [comment]
- You can restart php-fpm automatically in your deployment process by using the `fpm:reload` task. You can [read more about this in the documentation](https://github.com/lorisleiva/laravel-deployer/blob/919ea8386308d86837f434b69f40529854d15082/docs/how-to-reload-fpm.md#how-to-reload-php-fpm).

- If you're already using `fpm:reload` and still having this issue then — as mentioned in my previous comment — it is likely a problem with the OPcache not registering the new PHP files due to the symlinks. Following [this troubleshooting section](https://github.com/lorisleiva/laravel-deployer/blob/919ea8386308d86837f434b69f40529854d15082/docs/troubleshooting.md#my-changes-dont-show-up-after-a-deployment) should fix this issue.

Can anyone please let me know if they are still having this issue after following the two points above?

**Comment by MCMainiac** [comment]
Works like a charm! Didn't know about this task before... Guess I have to read the docs carefully next time. Btw nice job on the whole package! I love using it!

I had to custumize my command to: `'php_fpm_command' => 'echo "Reloading PHP-FPM" | sudo /bin/systemctl reload {{php_fpm_service}}',`

**Comment by lorisleiva** [comment]
Great! Thanks for sharing your php-fpm command. 🙂
