### ISSUE TITLE
Update for Laravel 5.8.*

### ISSUE THREAD

**Issue by MCMainiac** [lorisleiva/laravel-deployer#93]
I want to update to `laravel/framework 5.8` but `lorisleiva/laravel-deployer v0.2.7 requires illuminate/support 5.5.*|5.6.*`. The latest release has `illuminate/support 5.8.0`.

When can we expect an update?

**Comment by lorisleiva** [comment]
Yes sorry for the delay, it should be live in a few seconds. 🙂

**Comment by MCMainiac** [comment]
Thanks for the quick response!
