### ISSUE TITLE
Multiple production hosts

### ISSUE THREAD

**Issue by Salmondx** [lorisleiva/laravel-deployer#95]
Hello,
From the docs it was unclear for me about multiple hosts deployments. For example, I have 5-10 hosts with production tag. Is it possible to use `laravel-deployer` in this scenario?

From `deployer` I see that they support several ip addresses in `host` function.

Also, if this feature is supported, what deployment strategy you recommend? Local?

**Comment by lorisleiva** [comment]
Hi there 👋 

If I understand correctly, you're asking if there is a Laravel Deployer way to do this:

```php
host('110.164.16.59', '110.164.16.34', '110.164.16.50', ...)
    ->stage('production')
    ...
```

If so, the answer is yes but there is no "shortcut" to avoid duplicating the host settings yet I'm afraid.

```php
'hosts' => [
    '110.164.16.59' => [
        'deploy_path' => '/var/www/path',
        'stage' => 'production',
    ],
    '110.164.16.34' => [
        'deploy_path' => '/var/www/path',
        'stage' => 'production',
    ],
    '110.164.16.50' => [
        'deploy_path' => '/var/www/path',
        'stage' => 'production',
    ],
    ...
],
```

It would be nice for Laravel Deployer to offer a better way to deal with that though. If you have any syntax suggestions please don't hesitate.

Regarding the strategy, all of them can be used with multiple hosts. If you're not sure what to use, I'd stick with the `basic` strategy.

I hope this helps. 🙂

**Comment by Salmondx** [comment]
Thanks for response! Its a pity that there is no other way to reduce a config duplication, but I understand that its not your fault :)

**Comment by lorisleiva** [comment]
I suppose since the configurations are just PHP arrays, you could do something like:

```php
$hostOptions = [
    'deploy_path' => '/var/www/path',
    'stage' => 'production',
];

return [
    'hosts' => [
        '110.164.16.59' => $hostOptions,
        '110.164.16.34' => $hostOptions,
        '110.164.16.50' => $hostOptions,
        ...
    ],
];
```

**Comment by Salmondx** [comment]
That's exactly what I need, awesome. Thanks 👍

**Comment by lorisleiva** [comment]
I'm glad it helped 🙂
