### ISSUE TITLE
Writable chmod not working

### ISSUE THREAD

**Issue by emotality** [lorisleiva/laravel-deployer#96]
Hi Loris! I'm having issues with `chmod`. It doesn't wanna give access to my `storage` folder, after each deploy I have to manually ssh and give the folder access to write to storage.

Not sure what changed as I use the below options for all my projects and they work fine? Stopped working about 1 to 1.5 weeks ago.

```php
'options' => [
    'application'              => env('APP_NAME'),
    'repository'               => env('DEPLOYER_REPO'),
    'branch'                   => env('DEPLOYER_BRANCH', 'master'),
    'php_fpm_service'          => env('DEPLOYER_FPM', 'php7.2-fpm'),
    'default_timeout'          => 360,
    'keep_releases'            => 3,
    'release_name'             => date('YmdHi'),
    'composer_action'          => 'install',
    'composer_options'         => '{{composer_action}} --verbose --prefer-dist --no-progress --no-interaction --no-dev --optimize-autoloader',
    'ssh_multiplexing'         => true,
    'writable_use_sudo'        => true,
    'writable_chmod_recursive' => true,
    'writable_chmod_mode'      => 777,
    'writable_mode'            => 'chmod',
    'writable_dirs'            => [
        'bootstrap/cache',
        'storage',
    ],
    'shared_files'             => [
        '.env',
    ],
    'shared_dirs'              => [
        'storage',
    ],
],
```

Please advise?
Thanks a lot!

**Comment by MCMainiac** [comment]
In general: never give `777` on anything. This is probably not related to your issue, just common practice.

**Comment by emotality** [comment]
I knew that thanks, not the issue here :)

**Comment by lorisleiva** [comment]
Hi there 👋 

This must be an issue related to [DeployerPHP](https://github.com/deployphp/deployer) since Laravel Deployer is not affecting this behaviour.

I've had a look through DeployerPHP's issues and couldn't find anything recent on `chmod` issues.

Maybe it's a permission issue following some changes on your server.

I hope this helps, I'm not sure what else to suggest.

**Comment by emotality** [comment]
Thanks, will check with them 😄 

I create droplets from same Laravel snapshot I made, and it's only the recent projects that aren't working as the deployer versions are more up to date. 😬 I'll try using older version, thanks Loris!
