### ISSUE TITLE
Symlinks do not get created

### ISSUE THREAD

**Issue by tjventurini** [lorisleiva/laravel-deployer#97]
Trying to setup sqlite i added `database/database.sqlite` to `shared_files` array to `deploy.php` configuration but the symlink to the file is not in the current release.

```
        'shared_files' => [
            ".env",
            "database/database.sqlite",
        ],
```

Do I have to create them manually?

Thank you, package looking great so fare. This is my first issue with it :)

**Comment by tjventurini** [comment]
Ok, never mind. Don't know what changed exactly but it is working now. Thank you anyway :+1:

**Comment by lorisleiva** [comment]
Hi there 👋 

Thanks for the kind words, I'm glad you were able to solve this.

A lot of the symlink issues are related to the OPcache not detecting changes (See [troubleshooting section](https://github.com/lorisleiva/laravel-deployer/blob/master/docs/troubleshooting.md#my-changes-dont-show-up-after-a-deployment)).

If this happens again, feel free to reopen. 🙂
