### ISSUE TITLE
Bitbucket Repo Integration

### ISSUE THREAD

**Issue by paulkamau2015** [lorisleiva/laravel-deployer#98]
Hello. Thanks for building this package. It looks powerful and a money saver. 

Looking over your documentation, I don't see any mention of bitbucket. Does this package integrate with it? 
Thanks.

**Comment by lorisleiva** [comment]
Hi there 👋 

Yes, it works with any Git repository (GitHub, GitLab, Bitbucket, etc.).

Enjoy your deployments! 🙂
