### ISSUE TITLE
artisan:config:cache doesn't seem to run properly

### ISSUE THREAD

**Issue by Cookizza** [lorisleiva/laravel-deployer#99]
Hello,

I have noticed that once I deploy I need to SSH into my server and run 

    php artisan config:cache

If I don't do this then on form submissions I get a 419 across the site. However I can see this task is in my deploy file under the done section.

Very strange that running it from the server resolves the issue. I've tried moving around within deployer at what point that's triggered, but nada.

Any advice?

EDIT: I have found that if I am in SSH inside the `current` directory when i deploy, and then run the config cache clear command, i get the same result as deployer. I have to leave the symlink folder (current) and re-enter it after deploying to have the config cache clear correctly. Perhaps this is the same issue deployer is coming across?

**Comment by lorisleiva** [comment]
Hi there 👋 

When you `cd` to the `current` directory before the end of the deployment you will always end up in the previous stable release since the `current` symlink is changed at the very end of the deployment process to provide zero-downtime deployments. So that behaviour is normal.

However, I'm not sure why you'd need to manually refresh the config cache from the server since this is the entire point of the `artisan:config:cache` task.

Do you get an error in the console when reaching that task? May I see how you configure your `hooks` in the config file?

**Comment by Cookizza** [comment]
Hey @loganhenson thanks for a quick reply. Here is my hook file. I don't get any errors on console during deployment and my deployer ssh user is root so don't think it's permissions.

    'hooks' => [
        // Right before we start deploying.
        'start'   => [

        ],

        // Code and composer vendors are ready but nothing is built.
        'build'   => [

        ],

        // Deployment is done but not live yet (before symlink)
        'ready'   => [
            'artisan:storage:link',
        ],

        // Deployment is done and live
        'done'    => [
            'artisan:view:clear',
            'artisan:optimize',
            'artisan:cache:clear',
            'artisan:config:cache',
            'fpm:reload',
        ],

        // Deployment succeeded.
        'success' => [
        ],

        // Deployment failed.
        'fail'    => [
            //
        ],
    ],

    /*
    |--------------------------------------------------------------------------
    | Deployment options
    |--------------------------------------------------------------------------
    |
    | Options follow a simple key/value structure and are used within tasks
    | to make them more configurable and reusable. You can use options to
    | configure existing tasks or to use whithin your own custom tasks.
    |
    */

    'options' => [
        'php_fpm_service' => 'php7.2-fpm',
        'application'     => env('APP_NAME', 'Laravel'),
        'repository'      => 'git@bitbucket.org:xxx/xxx-laravel.git',
    ],

**Comment by loganhenson** [comment]
I assume you meant @lorisleiva 😄

**Comment by lorisleiva** [comment]
@Cookizza Everything seems correct on your config file. All I can think of is that it could be a symlink issue caused by OPcache. Could you try [this from the troubleshooting section](https://github.com/lorisleiva/laravel-deployer/blob/919ea8386308d86837f434b69f40529854d15082/docs/troubleshooting.md#my-changes-dont-show-up-after-a-deployment)?

**Comment by Cookizza** [comment]
Hey @lorisleiva - I've double checked those are in my nginx configs and indeed they are. Very strange

**Comment by lorisleiva** [comment]
Ergh... I'm really not sure what else to suggest. 🙁

Could you give more information on your server setup? Do you have any other applications on this server that do not have this issue?

**Comment by Cookizza** [comment]
It must be something on our setup. It happens on both staging and production. I think it's todo with the face we call for `env()` from our blade files and the cache doesn't like that.

I'll update with any findings

**Comment by lorisleiva** [comment]
Oh yeah, that is a big no-no for configuration caching:

<img width="749" alt="Screenshot 2019-03-25 at 12 04 53" src="https://user-images.githubusercontent.com/3642397/54918509-5b2b5a80-4ef6-11e9-9e85-39de731774da.png">

The `env()` function will always return `null` when the configuration is cached. So you can either not cache it at all (remove the `artisan:config:cache` from your deployment process) or replace all your loose `env()` calls by `config()` calls.
